begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values('a9000000-0000-4000-8000-000000000001','avatar_a@example.test'),('a9000000-0000-4000-8000-000000000002','avatar_b@example.test');
select set_config('request.jwt.claim.sub','a9000000-0000-4000-8000-000000000001',true);
select complete_onboarding('avatar_a','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
select set_config('request.jwt.claim.sub','a9000000-0000-4000-8000-000000000002',true);
select complete_onboarding('avatar_b','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
select is((select public from storage.buckets where id='profile-avatars'),false,'Avatar bucket remains private');
select is((select file_size_limit from storage.buckets where id='profile-avatars'),1048576::bigint,'Avatar compressed size is bounded');
select is((select allowed_mime_types from storage.buckets where id='profile-avatars'),array['image/jpeg'],'Only JPEG storage MIME allowed');
select set_config('request.jwt.claim.sub','a9000000-0000-4000-8000-000000000001',true);
create temporary table avatars(n integer,id uuid,path text);
grant all on avatars to authenticated;
set local role authenticated;
insert into avatars select 1,(v->'avatar'->>'id')::uuid,v->'avatar'->>'storage_path'
from (select reserve_profile_avatar('a9000000-0000-4000-8000-000000000101') v) q;
select is(get_own_avatar()->>'avatar_id',null,'Pending bytes do not appear as profile avatar');
select is(reserve_profile_avatar('a9000000-0000-4000-8000-000000000101')->'avatar'->>'id',(select id::text from avatars where n=1),'Reservation retry uses one immutable path');
select throws_ok($$select * from private.profile_avatars$$,'42501',null,'Private avatar source is not raw-readable');
select throws_ok($$select activate_profile_avatar((select id from avatars where n=1),auth.uid(),gen_random_uuid(),'version',repeat('a',64),16,16)$$,'42501',null,'Client cannot attest an avatar');
select throws_ok($$select * from get_avatar_targets(auth.uid(),array[(select id from avatars where n=1)])$$,'42501',null,'Signing lookup is service only');
select throws_ok($$select * from claim_avatar_cleanup()$$,'42501',null,'Cleanup authority is service only');
reset role;
select throws_ok($$insert into storage.objects(bucket_id,name,owner_id,version) values('profile-avatars','arbitrary.jpg',auth.uid()::text,'fake')$$,'23514','avatar_reservation_unavailable','Arbitrary paths denied at commit');
select throws_ok($$insert into storage.objects(bucket_id,name,owner_id,version) select 'profile-avatars',path,'a9000000-0000-4000-8000-000000000002','fake' from avatars where n=1$$,'23514','invalid_avatar_metadata','Foreign ownership denied at commit');
insert into storage.objects(bucket_id,name,owner_id,version,metadata) select 'profile-avatars',path,auth.uid()::text,'fixture-v1','{"mimetype":"image/jpeg","size":100}' from avatars where n=1;
select is(avatar_verification_target((select id from avatars where n=1),'a9000000-0000-4000-8000-000000000002'),null,'Verifier cannot inspect another owner reservation');
select throws_ok($$select activate_profile_avatar(a.id,auth.uid(),o.id,o.version,null,16,16) from avatars a join storage.objects o on o.name=a.path and o.bucket_id='profile-avatars' where a.n=1$$,'23514','invalid_avatar','Missing hash is rejected');
select throws_ok($$select activate_profile_avatar(a.id,auth.uid(),o.id,o.version,repeat('a',64),513,16) from avatars a join storage.objects o on o.name=a.path and o.bucket_id='profile-avatars' where a.n=1$$,'23514','invalid_avatar','Avatar dimensions enforced by DB');
select activate_profile_avatar(a.id,auth.uid(),o.id,o.version,repeat('a',64),16,16) from avatars a join storage.objects o on o.name=a.path and o.bucket_id='profile-avatars' where a.n=1;
select is(get_own_avatar()->>'avatar_id',(select id::text from avatars where n=1),'Verified avatar becomes current');
select is(get_public_profile()->'profile'->>'avatar_id',(select id::text from avatars where n=1),'Controlled public projection includes current avatar identifier');
select set_config('storage.allow_delete_query','true',true);
select throws_ok($$delete from storage.objects where bucket_id='profile-avatars' and name=(select path from avatars where n=1)$$,'23514','avatar_deletion_not_requested','Stale privileged cleanup cannot delete current avatar');
select throws_ok($$update storage.objects set version='changed' where bucket_id='profile-avatars' and name=(select path from avatars where n=1)$$,'23514','avatar_object_immutable','Verified object is immutable');
select set_config('request.jwt.claim.sub','a9000000-0000-4000-8000-000000000002',true);
select is((select count(*) from get_avatar_targets(auth.uid(),array[(select id from avatars where n=1)])),1::bigint,'Visible public profile avatar eligible for controlled signing');
insert into public.user_blocks(blocker_user_id,blocked_user_id) values(auth.uid(),'a9000000-0000-4000-8000-000000000001');
select is((select count(*) from get_avatar_targets(auth.uid(),array[(select id from avatars where n=1)])),0::bigint,'Block excludes avatar signing');
delete from public.user_blocks where blocker_user_id=auth.uid();
update private.safety_accounts set restricted=true where user_id='a9000000-0000-4000-8000-000000000001';
select is((select count(*) from get_avatar_targets(auth.uid(),array[(select id from avatars where n=1)])),0::bigint,'Restriction excludes public avatar signing');
select set_config('request.jwt.claim.sub','a9000000-0000-4000-8000-000000000001',true);
select is((select count(*) from get_avatar_targets(auth.uid(),array[(select id from avatars where n=1)])),1::bigint,'Restricted owner retains private avatar access');
update private.safety_accounts set restricted=false where user_id=auth.uid();
insert into avatars select 2,(v->'avatar'->>'id')::uuid,v->'avatar'->>'storage_path' from(select reserve_profile_avatar('a9000000-0000-4000-8000-000000000102') v) q;
insert into storage.objects(bucket_id,name,owner_id,version,metadata) select 'profile-avatars',path,auth.uid()::text,'fixture-v2','{"mimetype":"image/jpeg","size":100}' from avatars where n=2;
insert into avatars select 3,(v->'avatar'->>'id')::uuid,v->'avatar'->>'storage_path' from(select reserve_profile_avatar('a9000000-0000-4000-8000-000000000103') v) q;
select is(get_own_avatar()->>'avatar_id',(select id::text from avatars where n=1),'Reservation preserves previous current avatar until success');
select throws_ok($$select activate_profile_avatar(a.id,auth.uid(),o.id,o.version,repeat('a',64),16,16) from avatars a join storage.objects o on o.name=a.path and o.bucket_id='profile-avatars' where a.n=2$$,'42501','avatar_upload_expired','Later reservation fences old finalize');
insert into storage.objects(bucket_id,name,owner_id,version,metadata) select 'profile-avatars',path,auth.uid()::text,'fixture-v3','{"mimetype":"image/jpeg","size":100}' from avatars where n=3;
select activate_profile_avatar(a.id,auth.uid(),o.id,o.version,repeat('b',64),16,16) from avatars a join storage.objects o on o.name=a.path and o.bucket_id='profile-avatars' where a.n=3;
select is(get_own_avatar()->>'avatar_id',(select id::text from avatars where n=3),'Replacement becomes current atomically');
select is((select count(*) from private.profile_avatars where user_id=auth.uid() and status='current'),1::bigint,'Only one current avatar');
select is((select count(*) from get_avatar_targets(auth.uid(),array[(select id from avatars where n=1)])),0::bigint,'Retired avatar cannot be signed');
select is(remove_profile_avatar((select id from avatars where n=1))->>'avatar_id',(select id::text from avatars where n=3),'Old removal retry cannot remove newer avatar');
select is(remove_profile_avatar((select id from avatars where n=3))->>'avatar_id',null,'Current avatar removal restores initials');
select throws_ok($$select reserve_profile_avatar('a9000000-0000-4000-8000-000000000103')$$,'42501','avatar_upload_expired','Retired request tombstone cannot resurrect old upload');
select is((select count(*) from private.avatar_cleanup_queue where storage_path in(select path from avatars)),3::bigint,'Retired files have durable cleanup jobs');
select throws_ok($$select finish_avatar_cleanup((select path from avatars where n=3))$$,'23514','avatar_object_still_present','Physical deletion must precede cleanup acknowledgement');
select * from finish();
rollback;
