begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create temporary table people(n integer,owner uuid,id uuid);
create temporary table photos(id uuid);
create temporary table pages(payload jsonb);
create temporary table notifications(label text,id uuid);
do $$declare who uuid;i integer;begin
 for i in 1..27 loop
  who:=gen_random_uuid();
  insert into auth.users(id,email) values(who,'inbox_'||i||'@example.test');
  perform set_config('request.jwt.claim.sub',who::text,true);
  perform public.complete_onboarding('inbox_'||i,'00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','America/Toronto');
  insert into people select i,who,public_id from public.profiles where id=who;
 end loop;
end;$$;
create function pg_temp.capture() returns uuid language plpgsql as $$
declare challenge jsonb;s public.submissions;o storage.objects;assignment uuid;
begin
 challenge:=public.get_or_create_today_challenge();
 select id into assignment from public.daily_challenge_words where daily_challenge_id=(challenge->'challenge'->>'id')::uuid and slot='review' and replaced_at is null;
 s:=public.reserve_submission(assignment);
 insert into storage.objects(bucket_id,name,owner_id,version,metadata) values('challenge-submissions',s.storage_path,s.user_id::text,'inbox-fixture','{"mimetype":"image/jpeg","size":100}') returning * into o;
 perform public.attest_submission_photo(s.id,s.user_id,o.id,o.version,repeat('a',64),16,16);
 perform public.finalize_submission(s.id,'public');return s.id;
end;$$;
select set_config('request.jwt.claim.sub',(select owner::text from people where n=1),true);
insert into photos values(pg_temp.capture());
set constraints all immediate;
set constraints all deferred;
create temporary table xp_before as select * from public.xp_events;
select is((select count(*) from public.in_app_notifications where user_id=auth.uid() and kind='DAILY_WORDS_READY'),1::bigint,'Ready three-slot challenge creates one daily event independent of push opt-in');
select public.get_or_create_today_challenge();
select public.get_notification_summary();
select public.get_notification_inbox();
select is((select count(*) from public.in_app_notifications where user_id=auth.uid() and kind='DAILY_WORDS_READY'),1::bigint,'Challenge/inbox/summary retries do not duplicate daily event');
select public.replace_daily_challenge_word((select id from public.daily_challenge_words where daily_challenge_id=(select id from public.daily_challenges where user_id=auth.uid()) and slot='target' and replaced_at is null));
select is((select count(*) from public.in_app_notifications where user_id=auth.uid() and kind='DAILY_WORDS_READY'),1::bigint,'Word replacement does not create a new readiness event');
-- Only a current existing challenge is recovered after deployment, not all history.
delete from public.in_app_notifications where user_id=auth.uid() and kind='DAILY_WORDS_READY';
select public.get_notification_summary();
select is((select count(*) from public.in_app_notifications where user_id=auth.uid() and kind='DAILY_WORDS_READY'),1::bigint,'Current pre-migration challenge is recovered idempotently');
insert into public.user_follows(follower_user_id,followed_user_id)
 select owner,(select owner from people where n=1) from people where n between 2 and 26;
select is((select count(*) from public.in_app_notifications where user_id=auth.uid() and kind='NEW_FOLLOWER'),25::bigint,'One authoritative follower event per pair');
insert into notifications select 'daily',id from public.in_app_notifications where user_id=auth.uid() and kind='DAILY_WORDS_READY';
insert into notifications select 'follower',id from public.in_app_notifications where user_id=auth.uid() and actor_user_id=(select owner from people where n=2);
grant select on people,photos,pages,notifications to authenticated;
grant insert,delete on pages to authenticated;
set local role authenticated;
select is(jsonb_array_length(public.get_profile_connections((select id from people where n=27),'followers')->'items'),0,'An eligible profile can have an empty follower list');
select is(jsonb_array_length(public.get_profile_connections((select id from people where n=1),'followers')->'items'),20,'Followers list bounded to twenty by default');
insert into pages values(public.get_profile_connections((select id from people where n=1),'followers'));
select is((select payload->>'has_more' from pages),'true','Follower page exposes continuation');
select is(jsonb_array_length((select public.get_profile_connections((select id from people where n=1),'followers',(payload->'items'->19->>'followed_at')::timestamptz,(payload->'items'->19->>'id')::uuid)->'items' from pages)),5,'Timestamp ties paginate by public ID without missing or repeated followers');
select ok(not ((select payload->'items'->0 from pages) ?| array['owner_id','user_id','email','timezone','follower_user_id']),'Relationship projection exposes no private ownership or account fields');
select is((select payload->'profile'->>'follower_count' from pages),'25','Profile count agrees with visible list');
select is(jsonb_array_length(public.get_profile_connections((select id from people where n=2),'following')->'items'),1,'Following list points to followed profiles');
select is(public.get_profile_connections((select id from people where n=2),'following')->'items'->0->>'id',(select id::text from people where n=1),'Following row uses opaque profile identity');
select is(public.get_profile_connections((select id from people where n=2),'following')->'items'->0->>'is_self','true','List identifies current viewer and prevents offering self-follow');
select throws_ok($$select public.set_follow((select id from people where n=1),true)$$,'42501','follow_unavailable','Self-follow remains denied');
select throws_ok($$select public.get_profile_connections((select id from people where n=1),'bad')$$,'22023','invalid_connections_query','Unknown relationship direction rejected');
select throws_ok($$select public.get_profile_connections((select id from people where n=1),'followers',page_size=>25)$$,'22023','invalid_connections_query','Unbounded relationship read rejected');
select throws_ok($$select public.get_profile_connections((select id from people where n=1),'followers',before_id=>gen_random_uuid())$$,'22023','invalid_connections_query','Partial relationship cursor rejected');
select is(public.get_notification_summary()->>'unread_count','26','Unread count includes visible daily and social events');
select is(jsonb_array_length(public.get_notification_inbox()->'items'),20,'Inbox page bounded to twenty');
delete from pages;
insert into pages values(public.get_notification_inbox());
select is((select payload->>'has_more' from pages),'true','Inbox exposes continuation');
select is(jsonb_array_length((select public.get_notification_inbox((payload->'items'->19->>'created_at')::timestamptz,(payload->'items'->19->>'id')::uuid)->'items' from pages)),6,'Inbox keyset retrieves the remaining events without duplicates');
select ok(not ((select payload->'items'->0 from pages) ?| array['actor_user_id','user_id','source_key','email','storage_path','url']),'Inbox excludes private source identities and media capabilities');
select is(public.set_notification_read((select id from notifications where label='follower'),true)->>'unread_count','25','Read mutation updates authoritative unread count');
select is(public.set_notification_read((select id from notifications where label='follower'),true)->>'unread_count','25','Read retry is idempotent');
select is(public.set_notification_read((select id from notifications where label='follower'),false)->>'unread_count','26','Read event may be marked unread');
select is(public.resolve_notification_target((select id from notifications where label='follower'))->>'profile_id',(select id::text from people where n=2),'Follower target resolves current public profile');
select is(public.resolve_notification_target((select id from notifications where label='daily'))->>'kind','DAILY_WORDS_READY','Daily target uses fixed recognized kind');
select throws_ok($$select * from public.in_app_notifications$$,'42501',null,'Raw inbox reads denied even for owner');
select throws_ok($$insert into public.in_app_notifications(user_id,kind,source_key,actor_user_id) values(auth.uid(),'NEW_FOLLOWER','fake',gen_random_uuid())$$,'42501',null,'Clients cannot fabricate events');
select throws_ok($$update public.in_app_notifications set read_at=now()$$,'42501',null,'Direct REST read-state mutation denied');
select throws_ok($$delete from public.in_app_notifications$$,'42501',null,'Direct event deletion denied');
select throws_ok($$select public.get_notification_inbox(page_size=>25)$$,'22023','invalid_inbox_query','Inbox read bounded');
select throws_ok($$select public.get_notification_inbox(before_time=>'infinity',before_id=>gen_random_uuid())$$,'22023','invalid_inbox_query','Nonfinite inbox cursor denied');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=2),true);
select is(public.get_notification_summary()->>'unread_count','0','Other account cannot read recipient inbox');
select throws_ok($$select public.set_notification_read((select id from notifications where label='follower'),true)$$,'42501','notification_unavailable','Cross-user read-state modification denied');
select throws_ok($$select public.resolve_notification_target((select id from notifications where label='follower'))$$,'42501','notification_unavailable','Known cross-user event cannot resolve target');
select public.set_follow((select id from people where n=1),true);
select public.set_follow((select id from people where n=1),false);
select public.set_follow((select id from people where n=1),true);
select is(public.set_follow((select id from people where n=1),true)->'profile'->>'follower_count','25','Follow receipt carries authoritative target count');
select is(public.set_follow((select id from people where n=1),true)->'viewer_profile'->>'following_count','1','Follow receipt carries authoritative viewer count');
select ok(public.set_follow((select id from people where n=1),true)->>'followed_at' is not null,'Follow receipt supplies authoritative ordering timestamp');
select public.rate_submission((select id from photos),4);
select public.rate_submission((select id from photos),4);
select public.rate_submission((select id from photos),5);
reset role;
select is((select count(*) from public.in_app_notifications where user_id=(select owner from people where n=1) and actor_user_id=auth.uid() and kind='NEW_FOLLOWER'),1::bigint,'Unfollow/refollow and retries never duplicate follower notification');
select is((select count(*) from public.in_app_notifications where user_id=(select owner from people where n=1) and kind='NEW_RATING'),1::bigint,'Rating retries and score changes create only first rating notification');
insert into notifications select 'rating',id from public.in_app_notifications where user_id=(select owner from people where n=1) and kind='NEW_RATING';
select set_config('request.jwt.claim.sub',(select owner::text from people where n=1),true);
set local role authenticated;
select is(public.get_notification_inbox()->'items'->0->>'kind','NEW_RATING','New rating appears at top');
select is(public.get_notification_inbox()->'items'->0->>'username',null::text,'Rating never exposes rater identity');
select is(public.get_notification_inbox()->'items'->0->>'profile_id',null::text,'Rating cannot become rater-history/profile lookup');
select ok(not (public.get_notification_inbox()->'items'->0 ? 'score'),'Rating never exposes individual score');
select ok(public.resolve_notification_target((select id from notifications where label='rating'))->>'assignment_id' is not null,'Rating resolves only owned assignment context');
select throws_ok($$select public.rate_submission((select id from photos),5)$$,'42501','rating_unavailable','Self-rating still denied without notifications');
select public.mark_notifications_read((select (payload->'read_cursor'->>'time')::timestamptz from pages),(select (payload->'read_cursor'->>'id')::uuid from pages));
select is(public.get_notification_summary()->>'unread_count','1','Mark-all snapshot leaves newer rating unread');
select public.block_public_profile((select id from people where n=2));
select is(public.get_notification_summary()->>'unread_count','0','Blocked actor rating excluded from unread count');
select throws_ok($$select public.resolve_notification_target((select id from notifications where label='rating'))$$,'42501','notification_unavailable','Block immediately denies previously known rating target');
select is(jsonb_array_length(public.get_profile_connections((select id from people where n=1),'followers',page_size=>24)->'items'),24,'Blocked follower excluded from list');
select is(public.get_profile_connections((select id from people where n=1),'followers')->'profile'->>'follower_count','24','Blocked follower excluded from count');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=3),true);
select is(public.get_profile_connections((select id from people where n=1),'followers')->'profile'->>'follower_count','24','Profile-owner blocks exclude relationship for third-party viewer too');
select public.block_public_profile((select id from people where n=4));
select is(public.get_profile_connections((select id from people where n=1),'followers')->'profile'->>'follower_count','23','Third-party viewer blocks additionally reduce count');
reset role;
delete from public.user_blocks where blocker_user_id in(select owner from people);
select set_config('request.jwt.claim.sub',(select owner::text from people where n=1),true);
select public.set_submission_visibility((select id from photos),'private');
select throws_ok($$select public.resolve_notification_target((select id from notifications where label='rating'))$$,'42501','notification_unavailable','Private rating context cannot be opened through inbox');
select public.set_submission_visibility((select id from photos),'public');
insert into private.submission_moderation(submission_id,removed) values((select id from photos),true);
select throws_ok($$select public.resolve_notification_target((select id from notifications where label='rating'))$$,'42501','notification_unavailable','Removed rating context cannot be opened');
delete from private.submission_moderation where submission_id=(select id from photos);
update private.safety_accounts set restricted=true where user_id=(select owner from people where n=2);
select throws_ok($$select public.resolve_notification_target((select id from notifications where label='follower'))$$,'42501','notification_unavailable','Restricted actor follower notification hidden');
select throws_ok($$select public.resolve_notification_target((select id from notifications where label='rating'))$$,'42501','notification_unavailable','Restricted actor rating notification hidden');
update private.safety_accounts set restricted=false where user_id=(select owner from people where n=2);
update private.safety_accounts set restricted=true where user_id=auth.uid();
select is(jsonb_array_length(public.get_notification_inbox()->'items'),1,'Restricted recipient retains only private daily readiness');
update private.safety_accounts set restricted=false where user_id=auth.uid();
select public.begin_submission_deletion((select id from photos));
select throws_ok($$select public.resolve_notification_target((select id from notifications where label='rating'))$$,'42501','notification_unavailable','Deleting rating context excluded immediately');
select is((select jsonb_agg(to_jsonb(e) order by id) from public.xp_events e),(select jsonb_agg(to_jsonb(e) order by id) from xp_before e),'Inbox/follows/ratings/visibility/moderation do not alter XP');
select ok(not exists(select 1 from public.in_app_notifications where user_id=actor_user_id),'No self notifications exist');
select throws_ok($$update public.in_app_notifications set source_key='spoof'$$,'23514','immutable_notification_source','Durable event source identity cannot be rewritten');
select ok((select relrowsecurity from pg_class where oid='public.in_app_notifications'::regclass),'Inbox enables RLS with no raw ordinary policies');
set local role anon;
select throws_ok($$select public.get_notification_inbox()$$,'42501',null,'Anonymous inbox denied');
select throws_ok($$select public.get_profile_connections(gen_random_uuid(),'followers')$$,'42501',null,'Anonymous relationship projection denied');
reset role;
select ok(not has_function_privilege('authenticated','private.notify_new_follower()','execute'),'Clients cannot invoke notification generation authority');
select ok(not has_function_privilege('authenticated','private.ensure_daily_in_app_notification(uuid)','execute'),'Clients cannot fabricate another account daily event');
select * from finish();
rollback;
