begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create temporary table past_clock(instant timestamptz);
insert into past_clock values('2026-03-10 12:00:00+00');
create or replace function private.progress_time() returns timestamptz language sql volatile set search_path='' as $$select instant from pg_temp.past_clock$$;
create function pg_temp.clock_at(stamp timestamptz) returns void language sql as $$update pg_temp.past_clock set instant=stamp$$;
create function pg_temp.challenge(day date) returns uuid language plpgsql as $$
declare c uuid;
begin
 insert into public.daily_challenges(user_id,user_language_profile_id,created_at)
  select user_id,id,(day::timestamp+interval '12 hours') at time zone timezone from public.user_language_profiles where user_id=auth.uid() returning id into c;
 perform private.assign_challenge_word(c,'review');perform private.assign_challenge_word(c,'target');perform private.assign_challenge_word(c,'stretch');
 return c;
end;$$;
create function pg_temp.complete(sid uuid,which_visibility text default 'private') returns uuid language plpgsql as $$
declare s public.submissions;o storage.objects;
begin
 select * into strict s from public.submissions where id=sid;
 if s.status='completed' then perform public.finalize_submission(sid,which_visibility);return sid;end if;
 insert into storage.objects(bucket_id,name,owner_id,version,metadata)
  values('challenge-submissions',s.storage_path,s.user_id::text,'past-word-fixture','{"mimetype":"image/jpeg","size":100}') returning * into o;
 -- Real bytes and the Edge verifier are covered separately by Auth/Storage tests.
 perform public.attest_submission_photo(s.id,s.user_id,o.id,o.version,repeat('a',64),16,16);
 perform public.finalize_submission(s.id,which_visibility);return s.id;
end;$$;
create function pg_temp.erase(sid uuid) returns void language plpgsql as $$
begin
 perform public.begin_submission_deletion(sid);
 perform set_config('storage.allow_delete_query','true',true);
 delete from storage.objects where name=(select storage_path from public.submissions where id=sid);
 perform public.finish_submission_deletion(sid);
end;$$;
insert into auth.users(id,email) values
 ('7e000000-0000-4000-8000-000000000001','past_owner@example.test'),
 ('7e000000-0000-4000-8000-000000000002','past_other@example.test');
select set_config('request.jwt.claim.sub','7e000000-0000-4000-8000-000000000001',true);
select public.complete_onboarding('past_owner','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
create temporary table challenges(label text,id uuid);
insert into challenges values('old',pg_temp.challenge('2026-03-08')),('legacy',pg_temp.challenge('2026-03-09')),('today',pg_temp.challenge('2026-03-10'));
create temporary table assignments as select c.label,w.slot,w.id,w.daily_challenge_id from challenges c join public.daily_challenge_words w on w.daily_challenge_id=c.id;
create temporary table captures(label text,id uuid);
select is(jsonb_array_length(public.get_my_past_words()->'items'),6,'Only prior local dates appear, excluding today');
select is(public.get_my_past_words()->>'current_local_date','2026-03-10','Past Words uses the authoritative persisted-zone date');
select is(public.get_assignment_photo((select id from assignments where label='old' and slot='review'))->>'can_capture_historical','true','Missing past assignment permits historical capture');
select is(public.get_assignment_photo((select id from assignments where label='old' and slot='review'))->>'can_capture_daily','false','Missing past assignment cannot claim daily capture');
select is(public.get_assignment_photo((select id from assignments where label='today' and slot='review'))->>'can_capture_daily','true','Today retains daily capture admission');
select throws_ok($$select public.reserve_historical_submission((select id from assignments where label='today' and slot='review'))$$,'23514','historical_assignment_required','Current-day historical reservation rejected');
select throws_ok($$select public.reserve_submission((select id from assignments where label='old' and slot='review'))$$,'23514','past_word_requires_historical_capture','Old word cannot bypass historical semantics through daily REST RPC');
select throws_ok($$select public.reserve_historical_submission((select id from public.vocabulary_concepts limit 1))$$,'42501','assignment_unavailable','Arbitrary catalog concept is not an XP opportunity');
select public.replace_daily_challenge_word((select id from assignments where label='old' and slot='target'));
select throws_ok($$select public.reserve_historical_submission((select id from assignments where label='old' and slot='target'))$$,'42501','assignment_unavailable','Retired replacement is not eligible');
select ok(not exists(select 1 from jsonb_array_elements(public.get_my_past_words()->'items') i where i->>'assignment_id'=(select id::text from assignments where label='old' and slot='target')),'Replaced words do not leak into Past Words');
update assignments set id=(select w.id from public.daily_challenge_words w where w.daily_challenge_id=assignments.daily_challenge_id and w.slot=assignments.slot and w.replaced_at is null) where label='old' and slot='target';
insert into captures values('old-review',(public.reserve_historical_submission((select id from assignments where label='old' and slot='review'))).id);
select is((select capture_kind from public.submissions where id=(select id from captures where label='old-review')),'historical','Server reservation explicitly records immutable historical kind');
select is((public.reserve_historical_submission((select id from assignments where label='old' and slot='review'))).id,(select id from captures where label='old-review'),'Historical reserve retries reuse one row');
select throws_ok($$select public.reserve_submission((select id from assignments where label='old' and slot='review'))$$,'23514','capture_kind_conflict','Pending historical capture cannot be converted to daily');
select throws_ok($$update public.submissions set capture_kind='daily' where id=(select id from captures where label='old-review')$$,'23514','submission_identity_immutable','Even privileged ordinary updates cannot convert capture kind');
select throws_ok($$select public.finalize_submission((select id from captures where label='old-review'))$$,'23514','photo_not_uploaded','Historical path still requires uploaded image');
select pg_temp.complete((select id from captures where label='old-review'));
select is(public.get_my_progress()->>'total_xp','10','One historical capture earns exactly 10 XP');
select is(public.get_my_progress()->>'completed_words','0','Historical capture cannot complete a current-day word');
select is(public.get_my_progress((select id from challenges where label='old'))->>'completed_words','0','Historical capture cannot complete its old daily word');
select is(public.get_my_progress()->>'total_words_completed','0','Historical capture does not rewrite daily completion metrics');
select is(public.get_my_progress()->>'current_streak','0','Historical capture does not start a current streak');
select is(public.get_my_progress()->>'longest_streak','0','Historical capture does not manufacture historical streaks');
select is((select count(*) from private.word_completions where user_id=auth.uid()),0::bigint,'Historical capture never inserts a daily completion fact');
select is((select count(*) from private.qualified_days_seen where user_id=auth.uid()),0::bigint,'Historical capture never records a qualified day');
select is((select count(*) from private.streak_milestones where user_id=auth.uid()),0::bigint,'Historical capture never creates milestone candidates');
select is((select count(*) from private.historical_captures where user_id=auth.uid() and revoked_at is null),1::bigint,'Separate durable historical fact is recorded');
select throws_ok($$update private.historical_captures set captured_at=captured_at-interval '1 day' where user_id=auth.uid()$$,'23514','historical_capture_immutable','Historical fact identity and time are immutable');
select throws_ok($$update private.historical_captures set revoked_at=clock_timestamp() where user_id=auth.uid()$$,'23514','historical_capture_immutable','Fact cannot revoke before authoritative deletion');
select throws_ok($$delete from private.historical_captures where user_id=auth.uid()$$,'23514','historical_capture_immutable','Ordinary privileged maintenance cannot erase a live source fact');
select is(public.get_submission_xp((select id from captures where label='old-review'))->>'total_awarded_xp','10','Historical receipt reports normal 10 XP only');
select pg_temp.complete((select id from captures where label='old-review'));
select public.set_submission_visibility((select id from captures where label='old-review'),'public');
select public.set_submission_visibility((select id from captures where label='old-review'),'private');
select is((select count(*) from public.xp_events where user_id=auth.uid()),1::bigint,'Duplicate finalization and visibility edits create no duplicate XP events');
select is((public.reserve_historical_submission((select id from assignments where label='old' and slot='review'))).id,(select id from captures where label='old-review'),'Completed historical reservation remains idempotent');
select is(public.get_assignment_photo((select id from assignments where label='old' and slot='review'))->>'can_capture_historical','false','Completed entitlement cannot create another photo');
insert into captures select 'old-'||slot,pg_temp.complete((public.reserve_historical_submission(id)).id) from assignments where label='old' and slot in ('target','stretch');
select is(public.get_my_progress()->>'total_xp','30','Three historical captures earn only 30 XP');
select is(public.get_my_progress()->>'total_challenges_completed','0','Three historical captures never repair full-challenge metrics');
select is((select count(*) from public.xp_events where user_id=auth.uid() and event_type<>'WORD_COMPLETED'),0::bigint,'No daily or milestone bonus is awarded for historical captures');
select is(public.get_my_past_words()->'items'->0->>'has_capture','false','Missing words are prioritized ahead of captured words');
select is((select i->>'has_capture' from jsonb_array_elements(public.get_my_past_words()->'items') i where i->>'assignment_id'=(select id::text from assignments where label='old' and slot='review')),'true','Captured state is synchronized with authoritative submission');
select is(public.get_my_vocabulary()->>'total_concepts','3','Historical photos appear in the owner visual dictionary');
create temporary table pages(payload jsonb);
insert into pages values(public.get_my_past_words(page_size=>2));
select is((select payload->>'has_more' from pages),'true','Bounded Past Words pages advertise more');
select is(jsonb_array_length((select public.get_my_past_words(before_captured=>(payload->'items'->1->>'has_capture')::boolean,before_date=>(payload->'items'->1->>'challenge_date')::date,before_id=>(payload->'items'->1->>'assignment_id')::uuid,page_size=>2)->'items' from pages)),2,'Keyset crosses missing/captured partitions without dropping rows');
select is(jsonb_array_length(public.get_my_past_words(search_text=>upper((select target_term from public.daily_challenge_words where id=(select id from assignments where label='old' and slot='review'))))->'items')>=1,true,'Search is case-insensitive over immutable target snapshots');
select is(jsonb_array_length(public.get_my_past_words(search_text=>'%')->'items'),0,'Search metacharacters remain literal');
select ok(not exists(select 1 from jsonb_array_elements(public.get_my_past_words(requested_level=>'B1')->'items') i where i->>'cefr_level'<>'B1'),'CEFR filter is exact');
select throws_ok($$select public.get_my_past_words(page_size=>41)$$,'22023','invalid_past_words_query','Unbounded page request rejected');
select throws_ok($$select public.get_my_past_words(page_size=>0)$$,'22023','invalid_past_words_query','Empty page size rejected');
select throws_ok($$select public.get_my_past_words(search_text=>repeat('x',65))$$,'22023','invalid_past_words_query','Search input bounded');
select throws_ok($$select public.get_my_past_words(requested_level=>'D1')$$,'22023','invalid_past_words_query','Invalid CEFR rejected');
select throws_ok($$select public.get_my_past_words(before_captured=>false)$$,'22023','invalid_past_words_query','Partial keyset rejected');
select throws_ok($$select public.get_my_past_words(before_captured=>false,before_date=>'infinity',before_id=>gen_random_uuid())$$,'22023','invalid_past_words_query','Infinite keyset date rejected');
select public.begin_submission_deletion((select id from captures where label='old-review'));
select is(public.get_my_progress()->>'total_xp','30','Deletion intent retains entitlement until physical retirement');
select pg_temp.erase((select id from captures where label='old-review'));
select is(public.get_my_progress()->>'total_xp','20','Finished historical deletion reverses exactly 10 XP');
select is((select has_capture from private.past_word_entries where assignment_id=(select id from assignments where label='old' and slot='review')),false,'Finished deletion restores missing-photo list state');
select is(public.get_my_vocabulary()->>'total_concepts','2','Last historical capture deletion removes its visual dictionary entry');
update captures set id=pg_temp.complete((public.reserve_historical_submission((select id from assignments where label='old' and slot='review'))).id) where label='old-review';
select is(public.get_my_progress()->>'total_xp','30','Resubmission restores the same assignment entitlement');
select pg_temp.erase((select id from captures where label='old-review'));
update captures set id=pg_temp.complete((public.reserve_historical_submission((select id from assignments where label='old' and slot='review'))).id) where label='old-review';
select is(public.get_my_progress()->>'total_xp','30','Repeated delete/resubmit cannot farm net XP');
select is((select sum(amount) from public.xp_events where user_id=auth.uid() and source_key='word:'||(select id::text from assignments where label='old' and slot='review')),10::bigint,'Durable signed revisions retain exactly one net entitlement');
select is((select count(*) from public.xp_events where user_id=auth.uid() and source_key='word:'||(select id::text from assignments where label='old' and slot='review')),5::bigint,'Credits and reversals remain in durable history');
-- A ledger failure cannot leave a completed historical photo or partial fact.
select pg_temp.erase((select id from captures where label='old-review'));
update captures set id=(public.reserve_historical_submission((select id from assignments where label='old' and slot='review'))).id where label='old-review';
create function pg_temp.reject_historical_xp() returns trigger language plpgsql as $$begin raise exception 'injected_historical_xp_failure';end$$;
create trigger reject_historical_xp before insert on public.xp_events for each row execute function pg_temp.reject_historical_xp();
select throws_ok($$select pg_temp.complete((select id from captures where label='old-review'))$$,'P0001','injected_historical_xp_failure','Historical finalization rolls back when ledger insertion fails');
select is((select status from public.submissions where id=(select id from captures where label='old-review')),'pending','Failed ledger write cannot mark the photo completed');
select is((select count(*) from private.historical_captures where submission_id=(select id from captures where label='old-review')),0::bigint,'Failed ledger write leaves no partial historical fact');
select is(public.get_my_progress()->>'total_xp','20','Failed historical finalization leaves net XP unchanged');
select is((select has_capture from private.past_word_entries where assignment_id=(select id from assignments where label='old' and slot='review')),false,'Failed transaction rolls back the derived capture state');
drop trigger reject_historical_xp on public.xp_events;
select pg_temp.complete((select id from captures where label='old-review'));
select is(public.get_my_progress()->>'total_xp','30','Explicit retry after rolled-back ledger failure restores exactly 10 XP');
insert into captures select 'today-'||slot,pg_temp.complete((public.reserve_submission(id)).id) from assignments where label='today';
select is(public.get_my_progress()->>'total_xp','70','Current daily 3/3 still earns 40 XP alongside historical 30');
select is(public.get_my_progress()->>'completed_words','3','Current-day progress remains exactly 3/3');
select is(public.get_my_progress()->>'current_streak','1','Only current daily capture qualifies a streak day');
select is(public.get_my_progress()->>'total_challenges_completed','1','Only the current daily challenge is fully completed');
select throws_ok($$insert into private.historical_captures(submission_id,user_id,assignment_id,challenge_id,captured_at)
 select id,user_id,daily_challenge_word_id,daily_challenge_id,clock_timestamp() from public.submissions where id=(select id from captures where label='today-review')$$,'23514','invalid_historical_capture','Daily submission cannot be manufactured into a historical fact');
-- A reservation admitted while its day was current remains DAILY after midnight.
select pg_temp.clock_at('2026-03-09 12:00:00+00');
insert into captures values('legacy-review',(public.reserve_submission((select id from assignments where label='legacy' and slot='review'))).id);
select pg_temp.clock_at('2026-03-10 12:00:00+00');
select is((public.reserve_submission((select id from assignments where label='legacy' and slot='review'))).id,(select id from captures where label='legacy-review'),'Previously admitted daily upload recovers after midnight');
select throws_ok($$select public.reserve_historical_submission((select id from assignments where label='legacy' and slot='review'))$$,'23514','capture_kind_conflict','Historical path cannot steal a grandfathered daily reservation');
select pg_temp.complete((select id from captures where label='legacy-review'));
select is(public.get_my_progress((select id from challenges where label='legacy'))->>'completed_words','1','Existing interrupted daily capture retains original daily semantics');
insert into captures select 'legacy-'||slot,pg_temp.complete((public.reserve_historical_submission(id)).id) from assignments where label='legacy' and slot in ('target','stretch');
select is(public.get_my_progress((select id from challenges where label='legacy'))->>'completed_words','1','Mixed daily/historical captures cannot repair the old 3/3');
select is(public.get_my_progress()->>'total_challenges_completed','1','Mixed captures do not manufacture an old full-day bonus');
select pg_temp.erase((select id from captures where label='legacy-review'));
update captures set id=pg_temp.complete((public.reserve_historical_submission((select id from assignments where label='legacy' and slot='review'))).id) where label='legacy-review';
select is((select sum(amount) from public.xp_events where user_id=auth.uid() and source_key='word:'||(select id::text from assignments where label='legacy' and slot='review')),10::bigint,'Daily-to-historical replacement reuses one word entitlement');
select is(public.get_my_progress((select id from challenges where label='legacy'))->>'completed_words','0','Deleted daily fact is not restored by a historical replacement');
-- Persisted IANA boundaries, including DST's skipped and repeated clock hours.
update public.user_language_profiles set timezone='America/Toronto' where user_id=auth.uid();
select pg_temp.clock_at('2026-03-10 03:59:59+00');
select is(public.get_my_past_words()->>'current_local_date','2026-03-09','Toronto before midnight uses the previous local date');
select pg_temp.clock_at('2026-03-10 04:00:00+00');
select is(public.get_my_past_words()->>'current_local_date','2026-03-10','Toronto after spring DST midnight changes date at UTC04');
select pg_temp.clock_at('2026-11-01 05:30:00+00');
select is(public.get_my_past_words()->>'current_local_date','2026-11-01','First fall-back hour uses local calendar date');
select pg_temp.clock_at('2026-11-01 06:30:00+00');
select is(public.get_my_past_words()->>'current_local_date','2026-11-01','Repeated fall-back hour does not create another date');
-- Capture mode is fixed once admitted even when timezone travel moves the date back.
select pg_temp.clock_at('2026-03-10 12:00:00+00');
select pg_temp.erase((select id from captures where label='old-review'));
update captures set id=(public.reserve_historical_submission((select id from assignments where label='old' and slot='review'))).id where label='old-review';
select pg_temp.clock_at('2026-03-08 12:00:00+00');
select is(public.get_assignment_photo((select id from assignments where label='old' and slot='review'))->>'can_capture_historical','true','Admitted historical recovery survives a date moving back');
select pg_temp.complete((select id from captures where label='old-review'));
select is((select count(*) from private.word_completions where submission_id=(select id from captures where label='old-review')),0::bigint,'Timezone changes never convert admitted historical capture to daily');
select is(private.challenge_payload((select id from challenges where label='old'))->'words'->0->'submission'->>'capture_kind','historical','Challenge projection exposes historical photo kind after a date moves back');
select is(private.challenge_payload((select id from challenges where label='old'))->'words'->0->'submission'->>'status','completed','Challenge projection preserves the completed photo lifecycle');
select is(public.get_my_progress((select id from challenges where label='old'))->>'completed_words','0','Historical photo shown on a current-date challenge still contributes no daily completion');
select pg_temp.clock_at('2026-03-10 12:00:00+00');
-- Existing social authority consumes the same immutable completed photo projection.
select public.set_submission_visibility((select id from captures where label='old-review'),'public');
grant select on captures,assignments,challenges to authenticated;
select set_config('request.jwt.claim.sub','7e000000-0000-4000-8000-000000000002',true);
select public.complete_onboarding('past_other','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
set local role authenticated;
select is(jsonb_array_length(public.get_my_past_words()->'items'),0,'Another account cannot read the owner Past Words');
select is((select count(*) from public.submissions),0::bigint,'Raw submission RLS remains owner-only');
select is((select count(*) from public.xp_events),0::bigint,'Raw XP history remains owner-only');
select throws_ok($$select public.reserve_historical_submission((select id from assignments where label='old' and slot='review'))$$,'42501','assignment_unavailable','Cannot reserve another owner assignment');
select throws_ok($$select public.get_assignment_photo((select id from assignments where label='old' and slot='review'))$$,'42501','assignment_unavailable','Cannot inspect another owner photo context');
select throws_ok($$insert into public.submissions(daily_challenge_word_id,capture_kind) values((select id from assignments limit 1),'historical')$$,'42501',null,'Direct REST insertion cannot forge historical reservations');
select throws_ok($$update public.submissions set capture_kind='daily'$$,'42501',null,'Direct REST cannot modify capture authority');
select throws_ok($$select * from private.historical_captures$$,'42501',null,'Historical facts are private');
select throws_ok($$select * from private.past_word_entries$$,'42501',null,'Past Words index is private');
select throws_ok($$insert into public.xp_events(user_id,event_type,source_key,source_revision,amount,cause_submission_id) values(auth.uid(),'WORD_COMPLETED','fake',1,10,gen_random_uuid())$$,'42501',null,'Historical feature creates no direct XP mutation path');
select is(public.get_discover_submission((select id from captures where label='old-review'))->'items'->0->>'id',(select id::text from captures where label='old-review'),'Eligible public historical photo appears in Discover');
select is(public.rate_submission((select id from captures where label='old-review'),4)->'item'->>'rating_count','1','Historical photo uses normal rating authority');
select public.block_submission_user((select id from captures where label='old-review'));
select is(jsonb_array_length(public.get_discover_submission((select id from captures where label='old-review'))->'items'),0,'Mutual blocking hides historical public photos');
select throws_ok($$select public.rate_submission((select id from captures where label='old-review'),5)$$,'42501','rating_unavailable','Blocked historical photo cannot be rated');
reset role;
select ok(not has_function_privilege('anon','public.get_my_past_words(text,text,boolean,date,uuid,integer)','execute'),'Anonymous Past Words access denied');
select ok(not has_function_privilege('anon','public.reserve_historical_submission(uuid)','execute'),'Anonymous historical reservation denied');
select ok(not has_function_privilege('authenticated','private.photo_local_date(uuid)','execute'),'Client cannot probe another account timezone through helper');
select ok(not has_table_privilege('authenticated','private.historical_captures','insert'),'Client cannot manufacture historical facts');
select ok(not has_table_privilege('authenticated','private.past_word_entries','update'),'Client cannot manipulate missing-first projection');
select is((select count(*) from (select daily_challenge_word_id from public.submissions where status<>'deleted' group by 1 having count(*)>1) d),0::bigint,'One active reservation spans daily and historical kinds');
select is((select count(*) from private.past_word_entries e join public.daily_challenge_words w on w.id=e.assignment_id where w.replaced_at is not null),0::bigint,'Derived index never retains replaced assignments');
select is((select count(*) from private.past_word_entries e where e.has_capture is distinct from exists(select 1 from public.submissions s where s.daily_challenge_word_id=e.assignment_id and s.status in ('completed','deleting') and s.submitted_at is not null)),0::bigint,'Derived photo-state index remains synchronized through all lifecycle operations');
select * from finish();
rollback;
