begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values
 ('44000000-0000-4000-8000-000000000001','phase4a@example.test'),
 ('44000000-0000-4000-8000-000000000002','phase4b@example.test');
select set_config('request.jwt.claim.sub','44000000-0000-4000-8000-000000000001',true);
select public.complete_onboarding('phase4_a','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
create temporary table photo_fixture as select public.get_or_create_today_challenge() payload;
create temporary table reserved as select (public.reserve_submission((select (payload->'words'->0->>'id')::uuid from photo_fixture))).*;
grant select on photo_fixture,reserved to authenticated,anon;
select is((select public from storage.buckets where id='challenge-submissions'),false,'Photo bucket is private');
select is((select file_size_limit from storage.buckets where id='challenge-submissions'),5242880::bigint,'Bucket limits uploads to 5 MiB');
select is((select visibility from reserved),'private','Database reservation defaults to private');
select is((select status from reserved),'pending','An unuploaded reservation is not completed');
select is((select target_term from reserved),(select payload->'words'->0->>'target_term' from photo_fixture),'Text snapshot comes from the actual assignment');
select is((select concept_id from reserved),(select (payload->'words'->0->>'concept_id')::uuid from photo_fixture),'Concept comes from authoritative assignment');
set local role authenticated;
select is((public.reserve_submission((select daily_challenge_word_id from reserved))).id,(select id from reserved),'Repeated reserve returns the same ID');
select throws_ok($$select public.finalize_submission((select id from reserved))$$,'23514','photo_not_uploaded','Cannot finalize without stored object');
select throws_ok($$select public.replace_daily_challenge_word((select daily_challenge_word_id from reserved))$$,'23514','assignment_has_submission','Pending upload blocks conflicting replacement');
select throws_ok($$insert into public.submissions(daily_challenge_word_id) select daily_challenge_word_id from reserved$$,'42501',null,'Direct submission insert denied');
select throws_ok($$update public.submissions set status='completed' where id=(select id from reserved)$$,'42501',null,'Direct completion denied');
select throws_ok($$delete from public.submissions where id=(select id from reserved)$$,'42501',null,'Direct submission delete denied');
set local storage.operation='storage.object.upload';
select throws_ok($$insert into storage.objects(bucket_id,name) values('challenge-submissions','44000000-0000-4000-8000-000000000001/invented.jpg')$$,'23514','photo_reservation_unavailable','Unreserved owner-folder upload denied');
select throws_ok($$insert into storage.objects(bucket_id,name,user_metadata) select 'challenge-submissions',storage_path,'{"gps":"location"}'::jsonb from reserved$$,'23514','invalid_photo_metadata','Custom object metadata cannot store location information');
select lives_ok($$insert into storage.objects(bucket_id,name,owner_id,version,metadata) select 'challenge-submissions',storage_path,user_id::text,'fixture-version','{"mimetype":"image/jpeg","size":100}'::jsonb from reserved$$,'Owner may upload only the reserved object');
set local storage.operation='storage.object.get_authenticated';
select is((select count(*) from storage.objects where name=(select storage_path from reserved))::integer,1,'Owner can read uploaded object metadata');
-- Use row count rather than expecting an error for RLS-filtered UPDATE/DELETE.
with changed as(update storage.objects set metadata='{}' where name=(select storage_path from reserved) returning 1) select is(count(*)::integer,0,'Owner cannot overwrite stored object') from changed;
select throws_ok($$select public.finalize_submission((select id from reserved),'friends')$$,'23514','invalid_visibility','Invalid visibility rejected');
select throws_ok($$select public.finalize_submission((select id from reserved))$$,'23514','photo_not_verified','MIME metadata alone cannot complete an assignment');
reset role;
-- SQL fixture attests metadata only; real decoder validation is covered by integration tests.
select public.attest_submission_photo(r.id,r.user_id,o.id,o.version,repeat('a',64),16,16)
from reserved r join storage.objects o on o.name=r.storage_path;
set local role authenticated;
select is((public.finalize_submission((select id from reserved))).status,'completed','Valid upload finalizes successfully');
select is((public.finalize_submission((select id from reserved),'public')).visibility,'private','Uncertain-response retry cannot silently change saved visibility');
select is((public.reserve_submission((select daily_challenge_word_id from reserved))).id,(select id from reserved),'Completed assignment cannot get a second reservation');
select throws_ok($$select public.replace_daily_challenge_word((select daily_challenge_word_id from reserved))$$,'23514','assignment_has_submission','Completed assignment cannot be replaced');
select is((public.set_submission_visibility((select id from reserved),'public')).visibility,'public','Owner can change visibility');
reset role;
select ok(not has_function_privilege('authenticated','public.attest_submission_photo(uuid,uuid,uuid,text,text,integer,integer)','execute'),'Clients cannot fabricate verification receipts');
select ok(not has_function_privilege('anon','public.photo_verification_target(uuid,uuid)','execute'),'Anonymous callers cannot inspect verification targets');
select throws_ok($$update storage.objects set version='overwritten' where name=(select storage_path from reserved)$$,'23514','photo_object_immutable','Even elevated Storage commits cannot overwrite a photo');
select set_config('storage.allow_delete_query','true',true);
select throws_ok($$delete from storage.objects where name=(select storage_path from reserved)$$,'23514','photo_deletion_not_requested','Cleanup cannot delete a live completed image');
select is((select public from storage.buckets where id='challenge-submissions'),false,'Public visibility never publishes the bucket');
set local role authenticated;

set local storage.operation='storage.object.sign';
select is((select count(*) from storage.objects where name=(select storage_path from reserved))::integer,0,'Owner cannot use direct signing to bypass the fixed lifetime');
set local storage.operation='storage.object.sign_many';
select is((select count(*) from storage.objects where name=(select storage_path from reserved))::integer,0,'Batch signing does not bypass the lifetime');
set local storage.operation='storage.object.get_authenticated';
select set_config('request.jwt.claim.sub','44000000-0000-4000-8000-000000000002',true);
select is((select count(*) from public.submissions)::integer,0,'Other account cannot read even public-flagged submission');
select is((select count(*) from storage.objects where name=(select storage_path from reserved))::integer,0,'Other account cannot read photo');
select throws_ok($$select public.reserve_submission((select daily_challenge_word_id from reserved))$$,'42501',null,'Cannot submit for another user');
select throws_ok($$select public.finalize_submission((select id from reserved))$$,'42501','submission_unavailable','Cannot finalize another user submission');
select throws_ok($$select public.set_submission_visibility((select id from reserved),'private')$$,'42501','submission_unavailable','Public flag grants no visibility mutation rights');
select throws_ok($$select public.begin_submission_deletion((select id from reserved))$$,'42501','submission_unavailable','Cannot begin another user deletion');
select throws_ok($$insert into storage.objects(bucket_id,name) select 'challenge-submissions',storage_path from reserved$$,'23514','photo_reservation_unavailable','Cannot upload to another user reservation');
select throws_ok($$select public.claim_photo_cleanup()$$,'42501',null,'Client cannot invoke privileged cleanup');
select throws_ok($$select public.finish_photo_cleanup((select storage_path from reserved))$$,'42501',null,'Client cannot complete privileged cleanup');
reset role;
select ok(not has_function_privilege('anon','public.reserve_submission(uuid)','execute'),'Anonymous reservation denied');
select ok(not has_function_privilege('authenticated','private.prepare_submission()','execute'),'Definer helpers are not client callable');
select throws_ok($$update public.submissions set concept_id='44000000-0000-4000-8000-000000000003' where id=(select id from reserved)$$,'23514','submission_identity_immutable','Saved submission identity immutable even for maintenance');
select set_config('request.jwt.claim.sub','44000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select is((public.begin_submission_deletion((select id from reserved))).status,'deleting','Delete intent retains record until object removal');
select throws_ok($$select public.finish_submission_deletion((select id from reserved))$$,'23514','photo_not_deleted','Cannot release completion while image still exists');
reset role;
-- Metadata-only fixture, never a real uploaded blob. Production uses Storage API.
select set_config('storage.allow_delete_query','true',true);
set local role authenticated;
select set_config('request.jwt.claim.sub','44000000-0000-4000-8000-000000000002',true);
with removed as(delete from storage.objects where name=(select storage_path from reserved) returning 1) select is(count(*)::integer,0,'Other user cannot delete owner image') from removed;
select set_config('request.jwt.claim.sub','44000000-0000-4000-8000-000000000001',true);
with removed as(delete from storage.objects where name=(select storage_path from reserved) returning 1) select is(count(*)::integer,1,'Owner may remove object after delete intent') from removed;
select is((public.finish_submission_deletion((select id from reserved))).status,'deleted','Deletion retires submission after object removal');
select is((public.finish_submission_deletion((select id from reserved))).status,'deleted','Deletion retry is idempotent');
select is((select payload->'words'->0->>'id' from photo_fixture),(select public.get_or_create_today_challenge()->'words'->0->>'id'),'Deletion keeps original vocabulary assignment');
select ok(public.get_or_create_today_challenge()->'words'->0->'submission'='null'::jsonb,'Deleted photo restores incomplete card');
select isnt((public.reserve_submission((select daily_challenge_word_id from reserved))).id,(select id from reserved),'Owner can take a new photo after deletion');
select is((public.begin_submission_deletion((select id from reserved))).status,'deleted','Retrying old deletion cannot delete the new reservation');
reset role;
select * from finish();
rollback;
