begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
set local role authenticated;
select throws_ok($$select public.authorize_notification_attempt(gen_random_uuid())$$,'42501',null,'Users cannot obtain last-minute send authorization');
select throws_ok($$select public.claim_notification_attempts()$$,'42501',null,'Users cannot claim push send authority');
select throws_ok($$select public.claim_notification_receipts()$$,'42501',null,'Users cannot read private receipts');
select throws_ok($$select public.record_notification_result(gen_random_uuid(),'uncertain',null,'NetworkError')$$,'42501',null,'Users cannot modify outcomes');
select throws_ok($$select public.record_notification_receipt(gen_random_uuid(),gen_random_uuid(),'ok')$$,'42501',null,'Users cannot forge receipts');
select throws_ok($$select * from private.notification_attempt_events$$,'42501',null,'Cross-user attempt history is private');
reset role;
set local role service_role;
select throws_ok($$select * from private.notification_deliveries$$,'42501',null,'Service callers use controlled RPCs, not raw mutation grants');
select throws_ok($$select public.prepare_due_notifications()$$,'42501',null,'Legacy blocked preparation cannot consume new attempts');
reset role;
select throws_ok($$select public.claim_notification_attempts(51)$$,'22023','invalid_notification_batch','Send claims are bounded');
select throws_ok($$select public.claim_notification_receipts(101)$$,'22023','invalid_notification_batch','Receipt reads are bounded');
select throws_ok($$select public.record_notification_result(gen_random_uuid(),'ticket_accepted')$$,'22023','invalid_notification_result','Accepted ticket requires a provider ticket identity');
select throws_ok($$select public.record_notification_result(gen_random_uuid(),'send_rejected',null,'sensitive-token-text')$$,'22023','invalid_notification_result','Free-form provider content cannot enter results');
select throws_ok($$select public.record_notification_receipt(gen_random_uuid(),gen_random_uuid(),'error')$$,'22023','invalid_notification_receipt','Rejected receipt requires a safe error code');
select is(public.authorize_notification_attempt(null),false,'Missing notification cannot be authorized');
select * from finish();
rollback;
