begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values('77000000-0000-4000-8000-000000000001','discover_a@example.test'),('77000000-0000-4000-8000-000000000002','discover_b@example.test');
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
select public.complete_onboarding('discover_a','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
create temporary table photos(n integer,id uuid);
create function pg_temp.capture(day date) returns uuid language plpgsql as $$
declare c uuid;s public.submissions;o storage.objects;term uuid;
begin
 insert into public.daily_challenges(user_id,user_language_profile_id,created_at)
  select user_id,id,day::timestamp at time zone 'UTC' from public.user_language_profiles where user_id=auth.uid() returning id into c;
 select id into term from public.vocabulary_terms where language_id='00000000-0000-4000-8000-000000000002' and cefr_level='A2' order by id limit 1;
 insert into public.daily_challenge_words(daily_challenge_id,slot,cefr_level,vocabulary_term_id) values(c,'review','A2',term);
 perform private.assign_challenge_word(c,'target');perform private.assign_challenge_word(c,'stretch');
 s:=public.reserve_submission((select id from public.daily_challenge_words where daily_challenge_id=c and slot='review'));
 insert into storage.objects(bucket_id,name,owner_id,version,metadata) values('challenge-submissions',s.storage_path,s.user_id::text,'history-fixture','{"mimetype":"image/jpeg","size":100}') returning * into o;
 -- SQL metadata fixture only; real JPEG/Storage coverage is in the integration suite.
 perform public.attest_submission_photo(s.id,s.user_id,o.id,o.version,repeat('a',64),16,16);
 perform public.finalize_submission(s.id);return s.id;
end;
$$;
insert into photos values(1,pg_temp.capture('2026-08-01')),(2,pg_temp.capture('2026-08-02')),(3,pg_temp.capture('2026-08-03'));
select is(jsonb_array_length(public.get_discover_feed()->'items'),0,'Private captures excluded');
select public.set_submission_visibility(id,'public') from photos;
select is(jsonb_array_length(public.get_discover_feed()->'items'),3,'Own public captures appear, including repeated concepts');
-- Timestamp ties are fixture-only; production timestamps remain immutable.
alter table public.submissions disable trigger prepare_submission;
update public.submissions set submitted_at='2026-08-04T12:00:00.123456Z' where id in(select id from photos);
alter table public.submissions enable trigger prepare_submission;
create temporary table pages as select public.get_discover_feed(page_size=>1) payload;
select is((select payload->'items'->0->>'id' from pages),(select id::text from photos order by id desc limit 1),'Timestamp ties use descending UUID');
select is((select payload->>'has_more' from pages),'true','Lookahead indicates more');
select is((select public.get_discover_feed((payload->'items'->0->>'submitted_at')::timestamptz,(payload->'items'->0->>'id')::uuid,1)->'items'->0->>'id' from pages),(select id::text from photos order by id desc offset 1 limit 1),'Strict keyset has no duplicate under ties');
select is((select array_agg(key order by key) from jsonb_object_keys(public.get_discover_feed()->'items'->0) key),array['average_rating','can_rate','cefr_level','id','rating_count','reference_term','submitted_at','target_term','username','viewer_rating'],'Public projection contains only display fields');
update public.vocabulary_terms set term='Changed catalog',is_active=false where id=(select vocabulary_term_id from public.submissions where id=(select id from photos where n=1));
select isnt(public.get_discover_feed()->'items'->0->>'target_term','Changed catalog','Feed uses historical text');
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.get_discover_feed()$$,'42501','feed_unavailable','Incomplete viewer onboarding denied');
select public.complete_onboarding('discover_b','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
grant select on photos,pages to authenticated;
set local role authenticated;
select is(jsonb_array_length(public.get_discover_feed()->'items'),3,'Other onboarded viewer sees eligible public captures');
select is((select count(*) from public.submissions),0::bigint,'Raw submissions remain owner only');
select is((select count(*) from public.profiles where id='77000000-0000-4000-8000-000000000001'),0::bigint,'Private profile remains owner only');
select throws_ok($$update public.submissions set visibility='public'$$,'42501',null,'Direct mutation denied');
select throws_ok($$select * from private.discover_candidates$$,'42501',null,'Private view inaccessible');
select throws_ok($$select public.get_discover_photo_targets(auth.uid(),'00000000-0000-4000-8000-000000000002',array[(select id from photos limit 1)])$$,'42501',null,'Clients cannot invoke privileged signing lookup');
select throws_ok($$select public.get_discover_feed(page_size=>25)$$,'22023','invalid_feed_query','Page bounded');
select throws_ok($$select public.get_discover_feed(before_id=>gen_random_uuid())$$,'22023','invalid_feed_query','Partial cursor denied');
select throws_ok($$select public.get_discover_feed('infinity',gen_random_uuid(),1)$$,'22023','invalid_feed_query','Infinite cursor denied');
reset role;
update public.user_language_profiles set target_language_id='00000000-0000-4000-8000-000000000001',reference_language_id='00000000-0000-4000-8000-000000000002' where user_id=auth.uid();
select is(jsonb_array_length(public.get_discover_feed()->'items'),0,'Saved viewer target is authoritative');
select throws_ok($$select public.get_discover_photo_targets(auth.uid(),'00000000-0000-4000-8000-000000000002',array[(select id from photos limit 1)])$$,'42501','feed_settings_changed','Signer cannot override saved target');
select set_config('request.jwt.claim.sub','77000000-0000-4000-8000-000000000001',true);
select public.set_submission_visibility((select id from photos where n=1),'private');
select is(jsonb_array_length(public.get_discover_feed()->'items'),2,'Public to private removes eligibility');
select is((select count(*) from public.get_discover_photo_targets(auth.uid(),'00000000-0000-4000-8000-000000000002',array[(select id from photos where n=1)])),0::bigint,'Private image signing excluded even for owner feed');
select public.set_submission_visibility((select id from photos where n=1),'public');
select is(jsonb_array_length(public.get_discover_feed()->'items'),3,'Private to public restores eligibility');
update auth.users set banned_until=now()+interval '1 day' where id=auth.uid();
select is((select count(*) from private.discover_candidates),0::bigint,'Banned owner excluded');
select throws_ok($$select public.get_discover_feed()$$,'42501','feed_unavailable','Banned viewer denied');
update auth.users set banned_until=null,deleted_at=now() where id=auth.uid();
select is((select count(*) from private.discover_candidates),0::bigint,'Soft deleted account excluded');
update auth.users set deleted_at=null where id=auth.uid();
-- Simulate missing object metadata without weakening production guards.
set local session_replication_role=replica;
delete from storage.objects where name=(select storage_path from public.submissions where id=(select id from photos where n=3));
set local session_replication_role=origin;
select is(jsonb_array_length(public.get_discover_feed()->'items'),2,'Missing image excluded');
select public.begin_submission_deletion((select id from photos where n=2));
select is(jsonb_array_length(public.get_discover_feed()->'items'),1,'Deleting capture excluded');
select is((select count(*) from public.get_discover_photo_targets(auth.uid(),'00000000-0000-4000-8000-000000000002',array[(select id from photos where n=2)])),0::bigint,'Deleting photo cannot be newly signed');
select public.begin_submission_deletion((select id from photos where n=3));
select public.finish_submission_deletion((select id from photos where n=3));
select is(jsonb_array_length(public.get_discover_feed()->'items'),1,'Deleted capture excluded');
set local role anon;
select throws_ok($$select public.get_discover_feed()$$,'42501',null,'Anonymous feed denied');
reset role;
select ok((select prosecdef and proconfig @> array['search_path=""'] from pg_proc where oid='public.get_discover_feed(timestamptz,uuid,integer)'::regprocedure),'Definer uses fixed empty search path');
select is((select public from storage.buckets where id='challenge-submissions'),false,'Photo bucket remains private');
select * from finish();
rollback;
