begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values('79000000-0000-4000-8000-000000000001','safety_a@example.test'),('79000000-0000-4000-8000-000000000002','safety_b@example.test'),('79000000-0000-4000-8000-000000000003','safety_mod@example.test');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000001',true);
select public.complete_onboarding('safety_a','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000002',true);
select public.complete_onboarding('safety_b','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000003',true);
select public.complete_onboarding('safety_mod','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
insert into private.moderators(user_id) values(auth.uid());
create temporary table photos(n integer,id uuid);
create function pg_temp.capture(day date) returns uuid language plpgsql as $$
declare c uuid;s public.submissions;o storage.objects;term uuid;
begin
 insert into public.daily_challenges(user_id,user_language_profile_id,created_at)
  select user_id,id,day::timestamp at time zone 'UTC' from public.user_language_profiles where user_id=auth.uid() returning id into c;
 select id into term from public.vocabulary_terms where language_id='00000000-0000-4000-8000-000000000002' and cefr_level='A2' order by id limit 1;
 insert into public.daily_challenge_words(daily_challenge_id,slot,cefr_level,vocabulary_term_id) values(c,'review','A2',term);
 perform private.assign_challenge_word(c,'target');perform private.assign_challenge_word(c,'stretch');
 s:=public.reserve_submission((select id from public.daily_challenge_words where daily_challenge_id=c and slot='review'));
 insert into storage.objects(bucket_id,name,owner_id,version,metadata) values('challenge-submissions',s.storage_path,s.user_id::text,'history-fixture','{"mimetype":"image/jpeg","size":100}') returning * into o;
 -- SQL metadata fixture only; real JPEG/Storage coverage is in the integration suite.
 perform public.attest_submission_photo(s.id,s.user_id,o.id,o.version,repeat('a',64),16,16);
 perform public.finalize_submission(s.id);return s.id;
end;
$$;
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000001',true);
insert into photos values(1,pg_temp.capture('2026-08-01'));
select public.set_submission_visibility((select id from photos where n=1),'public');
select throws_ok($$select public.block_submission_user((select id from photos where n=1))$$,'42501','safety_unavailable','Self block rejected');
select throws_ok($$select public.report_public_content((select id from photos where n=1),'user','other')$$,'42501','safety_unavailable','Self report rejected');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000002',true);
insert into photos values(2,pg_temp.capture('2026-08-01'));
select public.set_submission_visibility((select id from photos where n=2),'public');
create temporary table xp_before as select * from public.xp_events;
grant select on photos to authenticated;
set local role authenticated;
select is(public.get_safety_access()->>'moderator','false','Ordinary learner is not moderator');
select is(public.report_public_content((select id from photos where n=1),'submission','privacy','Please review')->>'ok','true','Submission report acknowledged');
select is(public.report_public_content((select id from photos where n=1),'submission','other','duplicate')->>'ok','true','Duplicate report safely acknowledged');
select is(public.report_public_content((select id from photos where n=1),'user','spam')->>'ok','true','Account report acknowledged');
select throws_ok($$select public.report_public_content((select id from photos where n=1),'submission','invented')$$,'22023','invalid_report','Controlled reasons enforced');
select throws_ok($$select public.report_public_content((select id from photos where n=1),'submission','other',repeat('x',501))$$,'22023','invalid_report','Details bounded');
select throws_ok($$select public.report_public_content((select id from photos where n=1),'unknown','other')$$,'22023','invalid_report','Target kind controlled');
select throws_ok($$select * from public.safety_reports$$,'42501',null,'Reporter cannot read raw reports');
select throws_ok($$select * from public.user_blocks$$,'42501',null,'Block relationships are not raw-readable');
select throws_ok($$select * from public.moderation_audit$$,'42501',null,'Audit is not raw-readable');
select throws_ok($$insert into private.moderators(user_id) values(auth.uid())$$,'42501',null,'Cannot self-provision moderator');
select throws_ok($$update private.safety_accounts set restricted=false$$,'42501',null,'Cannot clear restrictions');
select throws_ok($$select public.get_moderation_queue()$$,'42501','moderation_unavailable','Queue denies ordinary users');
select throws_ok($$select public.get_moderation_report(gen_random_uuid())$$,'42501','moderation_unavailable','Detail denies ordinary users');
select throws_ok($$select public.get_moderation_history(gen_random_uuid())$$,'42501','moderation_unavailable','History denies ordinary users');
select throws_ok($$select public.moderate_report(gen_random_uuid(),'dismiss_report',gen_random_uuid())$$,'42501','moderation_unavailable','Ordinary moderator mutation denied');
select throws_ok($$select public.get_moderation_photo_target(auth.uid(),gen_random_uuid())$$,'42501',null,'Signing lookup is service only');
select public.rate_submission((select id from photos where n=1),4);
select is(public.block_submission_user((select id from photos where n=1))->>'ok','true','Block accepted');
select is(public.block_submission_user((select id from photos where n=1))->>'ok','true','Block retry idempotent');
select is(jsonb_array_length(public.get_blocked_users()->'items'),1,'One current block');
select is(jsonb_array_length(public.get_discover_feed()->'items'),1,'Blocker sees only own photo');
select throws_ok($$select public.rate_submission((select id from photos where n=1),3)$$,'42501','rating_unavailable','Blocker cannot rate blocked owner');
reset role;
select is((select count(*) from public.safety_reports),2::bigint,'Only one open report per kind/target');
select throws_ok($$update public.safety_reports set target_id=gen_random_uuid()$$,'23514',null,'Report target identity is a database invariant');
select is((select details from public.safety_reports where target_kind='submission'),'Please review','Duplicate cannot rewrite first report');
select is((select count(*) from public.submission_ratings),1::bigint,'Block preserves existing vote');
create temporary table blocks as select id from public.user_blocks;
create temporary table cases as select id,target_kind from public.safety_reports;
grant select on blocks,cases to authenticated;
select is((select count(*) from public.get_discover_photo_targets(auth.uid(),'00000000-0000-4000-8000-000000000002',array[(select id from photos where n=1)])),0::bigint,'Blocked photo has no signing target');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select is(jsonb_array_length(public.get_blocked_users()->'items'),0,'Target does not learn who blocked them');
select is(jsonb_array_length(public.get_discover_feed()->'items'),1,'Mutual block hides blocker photos');
select throws_ok($$select public.rate_submission((select id from photos where n=2),5)$$,'42501','rating_unavailable','Blocked user cannot rate blocker');
select public.unblock_user((select id from blocks));
select is(jsonb_array_length(public.get_discover_feed()->'items'),1,'Cannot unblock another user relationship');
select throws_ok($$select * from public.safety_reports$$,'42501',null,'Reported user cannot read reports');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000002',true);
select public.unblock_user((select id from blocks));select public.unblock_user((select id from blocks));
select is(jsonb_array_length(public.get_discover_feed()->'items'),2,'Unblock restores eligible feed');
select is(jsonb_array_length(public.get_blocked_users()->'items'),0,'Unblock retry stays removed');
reset role;
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000003',true);
set local role authenticated;
select is(public.get_safety_access()->>'moderator','true','Backend-provisioned moderator admitted');
select is(jsonb_array_length(public.get_moderation_queue()->'items'),2,'Moderator sees open reports');
select ok(not ((public.get_moderation_report((select id from cases where target_kind='submission'))->'report')?'reporter_user_id'),'Case projection omits reporter identity');
select throws_ok($$select public.get_moderation_queue(report_status=>'invented')$$,'22023','invalid_queue','Queue filter validated');
select public.moderate_report((select id from cases where target_kind='submission'),'remove_submission','79000000-0000-4000-8000-000000000010','Review');
select public.moderate_report((select id from cases where target_kind='submission'),'remove_submission','79000000-0000-4000-8000-000000000010','Review');
select is(public.get_moderation_report((select id from cases where target_kind='submission'))->>'removed','true','Moderator removal stored separately');
select throws_ok($$select public.moderate_report((select id from cases where target_kind='submission'),'restore_submission','79000000-0000-4000-8000-000000000010','Review')$$,'22023','request_identity_conflict','Cannot reuse request ID for different intent');
reset role;
select is((select count(*) from public.moderation_audit),1::bigint,'Retry creates one audit record');
select throws_ok($$update public.moderation_audit set reason='rewritten'$$,'42501','immutable_moderation_audit','Audit UPDATE rejected even by migration owner');
select throws_ok($$delete from public.moderation_audit$$,'42501','immutable_moderation_audit','Audit DELETE rejected even by migration owner');
select is((select count(*) from public.get_moderation_photo_target(auth.uid(),(select id from cases where target_kind='submission'))),1::bigint,'Moderator can review removed verified image');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000001',true);
select public.set_submission_visibility((select id from photos where n=1),'private');
select public.set_submission_visibility((select id from photos where n=1),'public');
select is((select status from public.submissions where id=(select id from photos where n=1)),'completed','Removal preserves completion');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000002',true);
select is(jsonb_array_length(public.get_discover_feed()->'items'),1,'Owner visibility changes cannot bypass removal');
select throws_ok($$select public.rate_submission((select id from photos where n=1),3)$$,'42501','rating_unavailable','Removed photo cannot be rated');
select is((select count(*) from public.get_discover_photo_targets(auth.uid(),'00000000-0000-4000-8000-000000000002',array[(select id from photos where n=1)])),0::bigint,'Removed photo cannot be publicly signed');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000003',true);
select public.moderate_report((select id from cases where target_kind='submission'),'restore_submission',gen_random_uuid());
select public.moderate_report((select id from cases where target_kind='submission'),'remove_submission','79000000-0000-4000-8000-000000000010','Review');
select is(public.get_moderation_report((select id from cases where target_kind='submission'))->>'removed','false','Retry of older removal never undoes later restore');
select public.moderate_report((select id from cases where target_kind='user'),'suspend_user',gen_random_uuid());
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000001',true);
select is(public.get_safety_access()->>'restricted','true','Restriction is backend state');
select throws_ok($$select public.get_discover_feed()$$,'42501','feed_unavailable','Existing session cannot bypass restriction');
select throws_ok($$select public.rate_submission((select id from photos where n=2),5)$$,'42501','feed_unavailable','Restricted user cannot rate');
select throws_ok($$select public.set_submission_visibility((select id from photos where n=1),'public')$$,'42501','feed_unavailable','Restricted user cannot publish');
select lives_ok($$select public.set_submission_visibility((select id from photos where n=1),'private')$$,'Private management remains available');
select is(public.get_my_vocabulary()->>'total_concepts','1','Private vocabulary survives restriction');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000002',true);
select is(jsonb_array_length(public.get_discover_feed()->'items'),1,'Restricted owner is hidden');
select set_config('request.jwt.claim.sub','79000000-0000-4000-8000-000000000003',true);
select public.moderate_report((select id from cases where target_kind='user'),'restore_user',gen_random_uuid());
select public.moderate_report((select id from cases where target_kind='user'),'resolve_report',gen_random_uuid());
select public.moderate_report((select id from cases where target_kind='submission'),'dismiss_report',gen_random_uuid());
select is(jsonb_array_length(public.get_moderation_queue()->'items'),0,'Resolved/dismissed cases leave open queue');
select is(jsonb_array_length(public.get_moderation_queue(report_status=>'resolved')->'items'),1,'Resolved reports remain reviewable');
select is(jsonb_array_length(public.get_moderation_queue(report_status=>'dismissed')->'items'),1,'Dismissed reports remain reviewable');
select public.moderate_report((select id from cases where target_kind='user'),'resolve_report',gen_random_uuid()) from generate_series(1,22);
select is(jsonb_array_length(public.get_moderation_history((select id from cases where target_kind='user'))->'items'),20,'Audit history is bounded');
select is(public.get_moderation_history((select id from cases where target_kind='user'))->>'has_more','true','Audit exposes older-page availability');
select ok(jsonb_array_length(public.get_moderation_history((select id from cases where target_kind='user'),(public.get_moderation_history((select id from cases where target_kind='user'))->'items'->19->>'id')::bigint)->'items')>0,'Older audit entries remain reachable');
select is((select jsonb_agg(to_jsonb(e) order by id) from public.xp_events e),(select jsonb_agg(to_jsonb(e) order by id) from xp_before e),'Safety operations do not change any XP event');
delete from private.moderators where user_id=auth.uid();
select throws_ok($$select public.get_moderation_queue()$$,'42501','moderation_unavailable','Operational revocation invalidates existing sessions');
set local role anon;
select throws_ok($$select public.block_submission_user(gen_random_uuid())$$,'42501',null,'Anonymous block denied');
select throws_ok($$select public.report_public_content(gen_random_uuid(),'user','other')$$,'42501',null,'Anonymous report denied');
select throws_ok($$select public.get_moderation_queue()$$,'42501',null,'Anonymous moderation denied');
reset role;
select * from finish();
rollback;
