begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values
 ('7a000000-0000-4000-8000-000000000001','social_a@example.test'),
 ('7a000000-0000-4000-8000-000000000002','social_b@example.test'),
 ('7a000000-0000-4000-8000-000000000003','social_c@example.test'),
 ('7a000000-0000-4000-8000-000000000004','social_mod@example.test');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000001',true);
select public.complete_onboarding('social_a','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000002',true);
select public.complete_onboarding('social_b','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000003',true);
select public.complete_onboarding('social_c','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000004',true);
select public.complete_onboarding('social_mod','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
insert into private.moderators(user_id) values(auth.uid());
create temporary table people as select username as original,id as owner,public_id as id from public.profiles where username like 'social_%';
create temporary table photos(id uuid);
create function pg_temp.capture() returns uuid language plpgsql as $$
declare challenge jsonb;s public.submissions;o storage.objects;assignment uuid;
begin
 challenge:=public.get_or_create_today_challenge();
 select id into assignment from public.daily_challenge_words where daily_challenge_id=(challenge->'challenge'->>'id')::uuid and slot='review' and replaced_at is null;
 s:=public.reserve_submission(assignment);
 insert into storage.objects(bucket_id,name,owner_id,version,metadata) values('challenge-submissions',s.storage_path,s.user_id::text,'social-fixture','{"mimetype":"image/jpeg","size":100}') returning * into o;
 perform public.attest_submission_photo(s.id,s.user_id,o.id,o.version,repeat('a',64),16,16);
 perform public.finalize_submission(s.id,'public');return s.id;
end;$$;
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000001',true);
insert into photos values(pg_temp.capture());
create temporary table xp_before as select * from public.xp_events;
create temporary table comment_ids(label text,id uuid);
create temporary table report_ids(id uuid);
create temporary table block_ids(id uuid);
grant select on people,photos,comment_ids,report_ids,block_ids to authenticated;
grant insert on comment_ids to authenticated;

set local role authenticated;
select ok((public.get_public_profile()->'profile'->>'id')::uuid<>auth.uid(),'Public identifier differs from Auth ownership UUID');
select ok(not (public.get_public_profile()->'profile' ?| array['email','timezone','user_id','owner_id','target_language_id']),'Public profile omits private account/learning data');
select is(public.get_public_profile()->'profile'->>'is_self','true','Own profile is identified');
select is(public.update_my_profile('  SOCIAL_A_NEW  ')->>'ok','true','Username edits normalize case and whitespace');
select is(public.get_public_profile()->'profile'->>'username','social_a_new','Profile exposes authoritative current username');
select is(public.get_public_profile()->'profile'->>'id',(select id::text from people where original='social_a'),'Username edit preserves public identity');
select is(public.update_learning_preferences('00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B2','America/Toronto')->>'ok','true','Learning preferences use existing authoritative validation');
select is(public.get_public_profile()->'profile'->>'username','social_a_new','Learning update never overwrites a changed username');
select throws_ok($$select public.update_learning_preferences('00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','invalid','UTC')$$,'23514',null,'Learning CEFR still constrained');
select throws_ok($$select public.update_learning_preferences('00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','invalid')$$,'23514','invalid_timezone','Learning timezone still constrained');
select throws_ok($$select public.update_my_profile('social_b')$$,'23505',null,'Username is unique case-insensitively');
select throws_ok($$select public.update_my_profile('bad name')$$,'23514','invalid_username','Username format enforced');
select throws_ok($$update public.profiles set public_id=gen_random_uuid()$$,'42501',null,'Public ID cannot be replaced by ordinary users');
select throws_ok($$select public.get_public_profile(gen_random_uuid())$$,'42501','profile_unavailable','Unknown public identity is unavailable');
select throws_ok($$select public.get_public_profile(gen_random_uuid(),gen_random_uuid())$$,'22023','invalid_profile_query','Ambiguous profile selector rejected');
select is(public.get_public_profile(submission_id=>(select id from photos))->'profile'->>'username','social_a_new','Post context resolves exact current author');
select is(jsonb_array_length(public.search_public_profiles('SOCIAL_')->'items'),4,'Literal prefix search is normalized and bounded');
select is(jsonb_array_length(public.search_public_profiles('social_a_')->'items'),1,'Underscore is a literal prefix character');
select throws_ok($$select public.search_public_profiles('%')$$,'22023','invalid_user_search','Wildcard broad search denied');
select throws_ok($$select public.search_public_profiles('s')$$,'22023','invalid_user_search','One-character database scan denied');
select throws_ok($$select public.search_public_profiles('social',after_id=>gen_random_uuid())$$,'22023','invalid_user_search','Unpaired search cursor denied');
select is(jsonb_array_length(public.search_public_profiles('social_',after_username=>'social_b',after_id=>(select id from people where original='social_b'))->'items'),2,'Search keyset advances without repeating tied username');
select throws_ok($$select public.set_follow((select id from people where original='social_a'),true)$$,'42501','follow_unavailable','Self-follow denied');
select is(public.set_follow((select id from people where original='social_b'),true)->>'ok','true','Following accepted');
select is(public.set_follow((select id from people where original='social_b'),true)->>'ok','true','Repeated follow is idempotent');
select is(public.get_public_profile((select id from people where original='social_b'))->'profile'->>'follower_count','1','Follow counts one edge');
select is(public.get_public_profile((select id from people where original='social_b'))->'profile'->>'is_following','true','Viewer relationship exposed without raw graph');
select is(public.get_public_profile()->'profile'->>'following_count','1','Own following count is correct');
select throws_ok($$select * from public.user_follows$$,'42501',null,'Raw social graph denied');
select throws_ok($$insert into public.user_follows values(auth.uid(),gen_random_uuid(),now())$$,'42501',null,'Direct follow mutation denied');
select is(public.set_follow((select id from people where original='social_b'),false)->>'ok','true','Unfollow accepted');
select is(public.set_follow((select id from people where original='social_b'),false)->>'ok','true','Unfollow retry remains removed');
select is(public.get_public_profile()->'profile'->>'following_count','0','Unfollow count reconciles');
select public.set_follow((select id from people where original='social_b'),true);
select public.block_public_profile((select id from people where original='social_b'));
select is(public.get_public_profile()->'profile'->>'following_count','0','Blocked relationship excluded from count');
select is(jsonb_array_length(public.search_public_profiles('social_b')->'items'),0,'Blocked profile hidden in search');
select throws_ok($$select public.get_public_profile((select id from people where original='social_b'))$$,'42501','profile_unavailable','Blocked public profile denied');
select throws_ok($$select public.set_follow((select id from people where original='social_b'),true)$$,'42501','follow_unavailable','Blocked follow denied');
reset role;
select throws_ok($$update public.profiles set public_id=gen_random_uuid() where id='7a000000-0000-4000-8000-000000000001'$$,'23514','immutable_public_profile_id','Stable public identity protected by database trigger');
insert into block_ids select id from public.user_blocks where blocker_user_id='7a000000-0000-4000-8000-000000000001';
select is((select count(*) from public.user_follows where follower_user_id='7a000000-0000-4000-8000-000000000001'),1::bigint,'Block preserves stored edge while hiding eligibility');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select is(jsonb_array_length(public.search_public_profiles('social_a')->'items'),0,'Block exclusion is mutual');
select is(public.get_public_profile()->'profile'->>'follower_count','0','Blocked follower hidden from target count');
select throws_ok($$select public.get_submission_comments((select id from photos))$$,'42501','comment_unavailable','Blocked photo comments inaccessible');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000001',true);
select public.unblock_user((select id from block_ids));
select is(public.get_public_profile()->'profile'->>'following_count','1','Unblock restores retained eligible edge');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.create_submission_comment((select id from photos),' ',gen_random_uuid())$$,'22023','invalid_comment','Blank comment denied');
select throws_ok($$select public.create_submission_comment((select id from photos),E'\t\n\r',gen_random_uuid())$$,'22023','invalid_comment','Control-whitespace-only comments denied');
select throws_ok($$select public.create_submission_comment((select id from photos),U&'\00A0\FEFF\2028',gen_random_uuid())$$,'22023','invalid_comment','Unicode-whitespace-only comments denied');
select throws_ok($$select public.create_submission_comment((select id from photos),repeat('x',501),gen_random_uuid())$$,'22023','invalid_comment','Comment length is server bounded');
select throws_ok($$select public.create_submission_comment((select id from photos),'Hi',null)$$,'22023','invalid_comment','Comment requires durable request identity');
insert into comment_ids values('first',(public.create_submission_comment((select id from photos),'  Clear meaning!  ','7a000000-0000-4000-8000-000000000101')->>'comment_id')::uuid);
select is(public.create_submission_comment((select id from photos),'Clear meaning!','7a000000-0000-4000-8000-000000000101')->>'comment_id',(select id::text from comment_ids where label='first'),'Create retry returns original comment');
select throws_ok($$select public.create_submission_comment((select id from photos),'Different','7a000000-0000-4000-8000-000000000101')$$,'22023','request_identity_conflict','Request identity cannot change body');
select throws_ok($$select public.create_submission_comment(null,'Clear meaning!','7a000000-0000-4000-8000-000000000101')$$,'22023','invalid_comment','Retry cannot erase its submission context');
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),1,'Retry creates only one visible comment');
select is(public.get_submission_comments((select id from photos))->'items'->0->>'body','Clear meaning!','Comment whitespace trimmed');
select is(public.get_submission_comments((select id from photos))->'items'->0->>'is_own','true','Viewer can identify own comment');
select ok(not (public.get_submission_comments((select id from photos))->'items'->0 ?| array['author_user_id','request_id','email']),'Comment projection omits private identity and request token');
select throws_ok($$select * from public.submission_comments$$,'42501',null,'Raw comments denied');
select throws_ok($$update public.submission_comments set removed=false$$,'42501',null,'Cannot directly restore moderation state');
select throws_ok($$select public.report_submission_comment((select id from comment_ids where label='first'),'spam')$$,'42501','safety_unavailable','Self-report denied');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000003',true);
select public.delete_submission_comment((select id from comment_ids where label='first'));
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),1,'Cannot delete another author comment');
select is(public.report_submission_comment((select id from comment_ids where label='first'),'privacy','Review text')->>'ok','true','Visible comment can be reported');
select is(public.report_submission_comment((select id from comment_ids where label='first'),'spam','Retry')->>'ok','true','Duplicate open comment report acknowledged');
select throws_ok($$select * from public.safety_reports$$,'42501',null,'Comment reporter cannot read private reports');
reset role;
insert into report_ids select id from public.safety_reports where target_kind='comment' and target_id=(select id from comment_ids where label='first');
select is((select count(*) from report_ids),1::bigint,'Only one open comment case retained');
select is((select comment_snapshot from public.safety_reports where id=(select id from report_ids)),'Clear meaning!','Case snapshots original comment text');
select throws_ok($$update public.submission_comments set body='rewritten'$$,'23514','immutable_comment','Comment history identity/text immutable');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select is(public.get_moderation_report((select id from report_ids))->>'comment_exists','true','Moderator receives comment case state');
select throws_ok($$select public.moderate_report((select id from report_ids),'remove_submission',gen_random_uuid())$$,'22023','invalid_moderation_action','Comment case cannot remove unrelated photo context');
select ok(not (public.get_moderation_report((select id from report_ids))->'report' ? 'reporter_user_id'),'Moderator projection hides reporter identity');
select public.moderate_report((select id from report_ids),'remove_comment','7a000000-0000-4000-8000-000000000102');
select public.moderate_report((select id from report_ids),'remove_comment','7a000000-0000-4000-8000-000000000102');
select is(public.get_moderation_report((select id from report_ids))->>'comment_removed','true','Moderator can remove reported comment');
select is(jsonb_array_length(public.get_moderation_history((select id from report_ids))->'items'),1,'Removal retry produces one durable audit');
reset role;
select is((select count(*) from public.get_moderation_photo_target(auth.uid(),(select id from report_ids))),0::bigint,'Comment report cannot authorize third-party private-photo inspection');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),0,'Moderator-removed comments are hidden');
select public.create_submission_comment((select id from photos),'Clear meaning!','7a000000-0000-4000-8000-000000000101');
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),0,'Create retry cannot restore moderation removal');
insert into comment_ids values('delete',(public.create_submission_comment((select id from photos),'Temporary','7a000000-0000-4000-8000-000000000103')->>'comment_id')::uuid);
select public.delete_submission_comment((select id from comment_ids where label='delete'));
select public.delete_submission_comment((select id from comment_ids where label='delete'));
select public.create_submission_comment((select id from photos),'Temporary','7a000000-0000-4000-8000-000000000103');
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),0,'Delete/create retries never resurrect a tombstone');
select public.create_submission_comment((select id from photos),'Page '||n,gen_random_uuid()) from generate_series(1,25)n;
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),20,'Comments page bounded at twenty');
select is(public.get_submission_comments((select id from photos))->>'has_more','true','Comment page exposes older availability');
select is(jsonb_array_length(public.get_submission_comments((select id from photos),
 (public.get_submission_comments((select id from photos))->'items'->19->>'created_at')::timestamptz,
 (public.get_submission_comments((select id from photos))->'items'->19->>'id')::uuid)->'items'),5,'Timestamp/UUID pagination traverses same-time comments exactly once');
select throws_ok($$select public.get_submission_comments((select id from photos),before_time=>now())$$,'22023','invalid_comment_query','Unpaired comment cursor denied');
select throws_ok($$select public.get_submission_comments((select id from photos),'infinity',gen_random_uuid())$$,'22023','invalid_comment_query','Nonfinite comment cursor denied');
insert into comment_ids values('unicode',(public.create_submission_comment((select id from photos),repeat(U&'\+01F600',500),gen_random_uuid())->>'comment_id')::uuid);
select is(public.get_submission_comments((select id from photos))->'items'->0->>'body',repeat(U&'\+01F600',500),'Comment limit counts Unicode characters rather than UTF-16 code units');
select public.delete_submission_comment((select id from comment_ids where label='unicode'));
insert into comment_ids values('blocked',(public.get_submission_comments((select id from photos))->'items'->0->>'id')::uuid);
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000003',true);
select public.block_public_profile((select id from people where original='social_b'));
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),0,'Blocked commenter hidden on another user post');
select throws_ok($$select public.report_submission_comment((select id from comment_ids where label='blocked'),'spam')$$,'42501','safety_unavailable','Previously known blocked comment cannot be reported');
select throws_ok($$select public.moderate_report((select id from report_ids),'remove_comment',gen_random_uuid())$$,'42501','moderation_unavailable','Ordinary viewer cannot remove a reported comment');
reset role;
delete from private.moderators where user_id='7a000000-0000-4000-8000-000000000004';
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select throws_ok($$select public.moderate_report((select id from report_ids),'remove_comment',gen_random_uuid())$$,'42501','moderation_unavailable','Revoked moderator cannot remove comments');
select throws_ok($$select public.get_moderation_report((select id from report_ids))$$,'42501','moderation_unavailable','Revoked moderator cannot read comment case snapshots');
reset role;
insert into private.moderators(user_id) values('7a000000-0000-4000-8000-000000000004');
update auth.users set banned_until=statement_timestamp()+interval '1 hour' where id='7a000000-0000-4000-8000-000000000002';
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),0,'Banned author comments are hidden');
select is(jsonb_array_length(public.search_public_profiles('social_b')->'items'),0,'Banned author cannot be found through search');
select is(public.get_public_profile()->'profile'->>'following_count','0','Banned follow target excluded from counts');
select throws_ok($$select public.get_public_profile((select id from people where original='social_b'))$$,'42501','profile_unavailable','Banned public profile unavailable by known identifier');
reset role;
update auth.users set banned_until=null,deleted_at=statement_timestamp() where id='7a000000-0000-4000-8000-000000000002';
set local role authenticated;
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),0,'Soft-deleted author comments are hidden');
select is(jsonb_array_length(public.search_public_profiles('social_b')->'items'),0,'Soft-deleted author excluded from search');
select is(public.get_public_profile()->'profile'->>'following_count','0','Soft-deleted follow target excluded from counts');
reset role;
update auth.users set deleted_at=null where id='7a000000-0000-4000-8000-000000000002';
set local role authenticated;
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000001',true);
select public.set_submission_visibility((select id from photos),'private');
select throws_ok($$select public.get_submission_comments((select id from photos))$$,'42501','comment_unavailable','Private parent excludes comments even for owner');
select throws_ok($$select public.create_submission_comment((select id from photos),'Hidden',gen_random_uuid())$$,'42501','comment_unavailable','Private parent rejects new comments');
select throws_ok($$select public.get_public_profile(submission_id=>(select id from photos))$$,'42501','profile_unavailable','Private post is not profile lookup context');
select public.set_submission_visibility((select id from photos),'public');
reset role;
update private.safety_accounts set restricted=true where user_id='7a000000-0000-4000-8000-000000000002';
set local role authenticated;
select is(jsonb_array_length(public.get_submission_comments((select id from photos))->'items'),0,'Restricted author comments hidden');
select is(public.get_public_profile()->'profile'->>'following_count','0','Restricted relationships excluded from counts');
select is(jsonb_array_length(public.search_public_profiles('social_b')->'items'),0,'Restricted profile hidden in search');
select set_config('request.jwt.claim.sub','7a000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.search_public_profiles('social')$$,'42501','feed_unavailable','Restricted viewer cannot discover people');
select throws_ok($$select public.create_submission_comment((select id from photos),'Denied',gen_random_uuid())$$,'42501','feed_unavailable','Restricted viewer cannot comment');
select lives_ok($$select public.update_my_profile('social_b_updated')$$,'Restriction preserves private profile editing');
select lives_ok($$select public.delete_submission_comment((select id from comment_ids where label='first'))$$,'Restriction preserves deleting own text');
reset role;
select is((select jsonb_agg(to_jsonb(e) order by id) from public.xp_events e),(select jsonb_agg(to_jsonb(e) order by id) from xp_before e),'Social operations do not change XP history');
set local role anon;
select throws_ok($$select public.search_public_profiles('social')$$,'42501',null,'Anonymous search denied');
select throws_ok($$select public.get_public_profile()$$,'42501',null,'Anonymous public profile denied');
select throws_ok($$select public.create_submission_comment(gen_random_uuid(),'Hi',gen_random_uuid())$$,'42501',null,'Anonymous comment denied');
select throws_ok($$select public.set_follow(gen_random_uuid(),true)$$,'42501',null,'Anonymous follow denied');
reset role;
select * from finish();
rollback;
