begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values
 ('7b000000-0000-4000-8000-000000000001','profile_posts_owner@example.test'),
 ('7b000000-0000-4000-8000-000000000002','profile_posts_viewer@example.test');
select set_config('request.jwt.claim.sub','7b000000-0000-4000-8000-000000000001',true);
select public.complete_onboarding('profile_posts_owner','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
select set_config('request.jwt.claim.sub','7b000000-0000-4000-8000-000000000002',true);
select public.complete_onboarding('profile_posts_viewer','00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','UTC');
create temporary table people as select id,public_id from public.profiles where id in('7b000000-0000-4000-8000-000000000001','7b000000-0000-4000-8000-000000000002');
create temporary table photos(n integer,id uuid);
create function pg_temp.capture(which_slot text,visibility text default 'public') returns uuid language plpgsql as $$
declare challenge jsonb;s public.submissions;o storage.objects;assignment uuid;
begin
 challenge:=public.get_or_create_today_challenge();
 select id into assignment from public.daily_challenge_words where daily_challenge_id=(challenge->'challenge'->>'id')::uuid and slot=which_slot and replaced_at is null;
 s:=public.reserve_submission(assignment);
 insert into storage.objects(bucket_id,name,owner_id,version,metadata) values('challenge-submissions',s.storage_path,s.user_id::text,'profile-posts-fixture','{"mimetype":"image/jpeg","size":100}') returning * into o;
 perform public.attest_submission_photo(s.id,s.user_id,o.id,o.version,repeat('a',64),16,16);
 perform public.finalize_submission(s.id,visibility);return s.id;
end;$$;
select set_config('request.jwt.claim.sub','7b000000-0000-4000-8000-000000000001',true);
insert into photos values(1,pg_temp.capture('review')),(2,pg_temp.capture('target')),(3,pg_temp.capture('stretch','private'));
select set_config('request.jwt.claim.sub','7b000000-0000-4000-8000-000000000002',true);
insert into photos values(4,pg_temp.capture('review'));
-- Tie only the fixture timestamps. Production submission timestamps stay immutable.
alter table public.submissions disable trigger prepare_submission;
update public.submissions set submitted_at='2026-09-20T12:00:00.123456Z' where id in(select id from photos);
alter table public.submissions enable trigger prepare_submission;
create temporary table pages(payload jsonb);
grant select on people,photos,pages to authenticated;
grant insert on pages to authenticated;
set local role authenticated;
select is(jsonb_array_length(public.get_public_profile_submissions((select public_id from people where id=auth.uid()))->'items'),1,'Viewer sees only their own public profile submissions');
select is(jsonb_array_length(public.get_public_profile_submissions((select public_id from people where id<>auth.uid()))->'items'),2,'Another viewer sees only the selected owner public submissions');
select is((select count(*) from public.submissions),1::bigint,'Profile RPC leaves raw cross-user submissions RLS intact');
select ok(not (public.get_public_profile_submissions((select public_id from people where id<>auth.uid()))->'items'->0 ?| array['user_id','owner_id','email','storage_path','daily_challenge_word_id']),'Profile posts expose only the existing minimized feed fields');
select is(public.get_public_profile_submissions((select public_id from people where id<>auth.uid()))->'items'->0->>'can_rate','true','Other viewer may rate an eligible owner post');
insert into pages values(public.get_public_profile_submissions((select public_id from people where id<>auth.uid()),page_size=>1));
select is((select payload->>'has_more' from pages),'true','Profile page lookahead reports more');
select is((select payload->'items'->0->>'id' from pages),(select id::text from photos where n in(1,2) order by id desc limit 1),'Profile ordering breaks equal timestamps by descending UUID');
select is((select public.get_public_profile_submissions((select public_id from people where id<>auth.uid()),(payload->'items'->0->>'submitted_at')::timestamptz,(payload->'items'->0->>'id')::uuid,1)->'items'->0->>'id' from pages),(select id::text from photos where n in(1,2) order by id desc offset 1 limit 1),'Profile keyset does not duplicate or skip timestamp ties');
select throws_ok($$select public.get_public_profile_submissions(auth.uid())$$,'42501','profile_unavailable','Auth ownership UUID is not a public profile selector');
select throws_ok($$select public.get_public_profile_submissions(null)$$,'22023','invalid_profile_feed_query','Missing profile selector denied');
select throws_ok($$select public.get_public_profile_submissions((select public_id from people where id=auth.uid()),page_size=>25)$$,'22023','invalid_profile_feed_query','Profile page is bounded');
select throws_ok($$select public.get_public_profile_submissions((select public_id from people where id=auth.uid()),before_id=>gen_random_uuid())$$,'22023','invalid_profile_feed_query','Partial profile cursor denied');
select throws_ok($$select public.get_public_profile_submissions((select public_id from people where id=auth.uid()),'infinity',gen_random_uuid())$$,'22023','invalid_profile_feed_query','Nonfinite profile cursor denied');
select public.block_public_profile((select public_id from people where id<>auth.uid()));
select throws_ok($$select public.get_public_profile_submissions((select public_id from people where id<>auth.uid()))$$,'42501','profile_unavailable','Blocked owner profile posts denied');
select set_config('request.jwt.claim.sub','7b000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.get_public_profile_submissions((select public_id from people where id<>auth.uid()))$$,'42501','profile_unavailable','Reverse block also denies profile posts');
select is(jsonb_array_length(public.get_public_profile_submissions((select public_id from people where id=auth.uid()))->'items'),2,'Owner public profile never includes owner private capture');
select is(public.get_public_profile_submissions((select public_id from people where id=auth.uid()))->'items'->0->>'can_rate','false','Own public profile does not permit self-rating');
reset role;
delete from public.user_blocks where blocker_user_id='7b000000-0000-4000-8000-000000000002';
insert into private.submission_moderation(submission_id,removed) values((select id from photos where n=1),true);
select is(jsonb_array_length(public.get_public_profile_submissions((select public_id from people where id=auth.uid()))->'items'),1,'Moderation removal hides own public post without changing completion');
select public.set_submission_visibility((select id from photos where n=1),'public');
select is(jsonb_array_length(public.get_public_profile_submissions((select public_id from people where id=auth.uid()))->'items'),1,'Visibility change cannot restore removed profile post');
delete from private.submission_moderation where submission_id=(select id from photos where n=1);
select public.begin_submission_deletion((select id from photos where n=1));
select is(jsonb_array_length(public.get_public_profile_submissions((select public_id from people where id=auth.uid()))->'items'),1,'Deleting profile post is excluded');
select public.set_submission_visibility((select id from photos where n=2),'private');
select is(jsonb_array_length(public.get_public_profile_submissions((select public_id from people where id=auth.uid()))->'items'),0,'Public to private immediately excludes profile post');
select public.set_submission_visibility((select id from photos where n=2),'public');
select is(jsonb_array_length(public.get_public_profile_submissions((select public_id from people where id=auth.uid()))->'items'),1,'Private to public restores currently eligible post');
update public.user_language_profiles set target_language_id='00000000-0000-4000-8000-000000000001',reference_language_id='00000000-0000-4000-8000-000000000002' where user_id=auth.uid();
select is(jsonb_array_length(public.get_public_profile_submissions((select public_id from people where id=auth.uid()))->'items'),0,'Owner profile still respects current saved target language');
select set_config('request.jwt.claim.sub','7b000000-0000-4000-8000-000000000002',true);
update private.safety_accounts set restricted=true where user_id='7b000000-0000-4000-8000-000000000001';
select throws_ok($$select public.get_public_profile_submissions((select public_id from people where id<>auth.uid()))$$,'42501','profile_unavailable','Restricted owner cannot appear through profile posts');
update private.safety_accounts set restricted=false where user_id='7b000000-0000-4000-8000-000000000001';
update auth.users set banned_until=now()+interval '1 day' where id='7b000000-0000-4000-8000-000000000001';
select throws_ok($$select public.get_public_profile_submissions((select public_id from people where id<>auth.uid()))$$,'42501','profile_unavailable','Banned owner cannot appear through profile posts');
set local role anon;
select throws_ok($$select public.get_public_profile_submissions(gen_random_uuid())$$,'42501',null,'Anonymous profile feed denied');
reset role;
select ok((select prosecdef and proconfig @> array['search_path=""'] from pg_proc where oid='public.get_public_profile_submissions(uuid,timestamptz,uuid,integer)'::regprocedure),'Profile feed uses hardened security definer');
select is((select public from storage.buckets where id='challenge-submissions'),false,'Profile posts do not change private bucket');
select * from finish();
rollback;
