begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create temporary table people(n integer,owner uuid,id uuid);
create temporary table photos(id uuid);
create temporary table pages(payload jsonb);
create temporary table notifications(label text,id uuid);
do $$declare who uuid;i integer;begin
 for i in 1..3 loop
  who:=gen_random_uuid();
  insert into auth.users(id,email) values(who,'qa28_'||i||'@example.test');
  perform set_config('request.jwt.claim.sub',who::text,true);
  perform public.complete_onboarding('qa28_'||i,'00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','B1','America/Toronto');
  insert into people select i,who,public_id from public.profiles where id=who;
 end loop;
end;$$;
create function pg_temp.capture() returns uuid language plpgsql as $$
declare challenge jsonb;s public.submissions;o storage.objects;assignment uuid;
begin
 challenge:=public.get_or_create_today_challenge();
 select id into assignment from public.daily_challenge_words where daily_challenge_id=(challenge->'challenge'->>'id')::uuid and slot='review' and replaced_at is null;
 s:=public.reserve_submission(assignment);
 insert into storage.objects(bucket_id,name,owner_id,version,metadata) values('challenge-submissions',s.storage_path,s.user_id::text,'inbox-fixture','{"mimetype":"image/jpeg","size":100}') returning * into o;
 perform public.attest_submission_photo(s.id,s.user_id,o.id,o.version,repeat('a',64),16,16);
 perform public.finalize_submission(s.id,'public');return s.id;
end;$$;
select set_config('request.jwt.claim.sub',(select owner::text from people where n=1),true);
insert into photos values(pg_temp.capture());
set constraints all immediate;
set constraints all deferred;
create temporary table saved(label text primary key,value jsonb);
create temporary table concepts as select concept_id from public.submissions where id=(select id from photos);
grant select on people,photos,concepts,saved to authenticated;
grant insert,delete on saved to authenticated;
set local role authenticated;
select is(public.get_explore_concept((select concept_id from concepts))->'item'->>'has_captures','true','Only real owned completed captures admit history');
select is(public.get_public_profile((select id from people where n=1))->'profile'->>'level','1','Public Level starts at one');
select ok(not(public.get_public_profile((select id from people where n=1))->'profile' ?| array['total_xp','xp_events','current_streak','longest_streak','timezone','email','user_id']),'Public projection includes no private progression or profile fields');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=2),true);
select is(public.get_explore_concept((select concept_id from concepts))->'item'->>'has_captures','false','Other users capture does not admit owner history');
select public.set_follow((select id from people where n=1),true);
select public.rate_submission((select id from photos),4);
select set_config('request.jwt.claim.sub',(select owner::text from people where n=1),true);
select is(public.resolve_notification_target((select (x->>'id')::uuid from jsonb_array_elements(public.get_notification_inbox()->'items') x where x->>'kind'='NEW_RATING'))->>'submission_id',(select id::text from photos),'Rating resolves canonical post without exposing rater identity');
insert into saved values('first',public.open_notification_inbox('91000000-0000-4000-8000-000000000001'));
select is((select value->>'unread_count' from saved where label='first'),'0','Opening marks existing eligible daily/follower/rating rows');
select is(public.get_notification_summary()->>'unread_count','0','Badge follows persisted authoritative read state');
select ok(not exists(select 1 from jsonb_array_elements(public.get_notification_inbox()->'items') x where x->>'read_at' is null),'History remains with persisted read times');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=3),true);
select public.set_follow((select id from people where n=1),true);
select set_config('request.jwt.claim.sub',(select owner::text from people where n=1),true);
select is(public.get_notification_summary()->>'unread_count','1','A later new event remains unread');
select is(public.open_notification_inbox('91000000-0000-4000-8000-000000000001')->>'unread_count','1','Retrying old opening cannot clear new event');
select is(public.open_notification_inbox('91000000-0000-4000-8000-000000000001')->>'opened_at',(select value->>'opened_at' from saved where label='first'),'Retry retains exact server cutoff');
select throws_ok($$select public.open_notification_inbox(null)$$,'22023','invalid_inbox_open','Null idempotency key denied');
select throws_ok($$select public.open_notification_inbox(gen_random_uuid(),array[gen_random_uuid(),null])$$,'22023','invalid_inbox_open','Null displayed IDs denied');
select throws_ok($$select public.open_notification_inbox(gen_random_uuid(),array_fill(gen_random_uuid(),array[61]))$$,'22023','invalid_inbox_open','Unbounded displayed state denied');
select throws_ok($$select * from private.inbox_openings$$,'42501',null,'Opening receipts are not a public read API');
select throws_ok($$update public.in_app_notifications set read_at=now()$$,'42501',null,'Direct notification read writes remain denied');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=2),true);
select is(public.open_notification_inbox('91000000-0000-4000-8000-000000000001')->>'unread_count','0','Same request ID is isolated to own inbox');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=1),true);
select is(public.get_notification_summary()->>'unread_count','1','Cross-account opening cannot alter original unread state');
select is(public.open_notification_inbox('91000000-0000-4000-8000-000000000002')->>'unread_count','0','An explicit later opening admits later events');
select public.block_public_profile((select id from people where n=2));
insert into saved values('block',public.get_blocked_users()->'items'->0);
select is(public.get_blocked_profile((select (value->>'id')::uuid from saved where label='block'))->'profile',(select value from saved where label='block'),'Blocked recognition uses same bounded identity projection');
select is((select array_agg(key order by key) from jsonb_object_keys(public.get_blocked_profile((select (value->>'id')::uuid from saved where label='block'))->'profile') key),array['avatar_id','id','username'],'Recognition exposes exactly block ID, username and nullable avatar reference');
select throws_ok($$select public.get_public_profile((select id from people where n=2))$$,'42501','profile_unavailable','Recognition does not restore public profile or Level eligibility');
select throws_ok($$select public.get_profile_connections((select id from people where n=2),'followers')$$,'42501','profile_unavailable','Recognition does not restore relationship browsing');
select throws_ok($$select public.get_blocked_avatar_targets(auth.uid(),array[gen_random_uuid()])$$,'42501',null,'Client cannot choose signing viewer');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=3),true);
select throws_ok($$select public.get_blocked_profile((select (value->>'id')::uuid from saved where label='block'))$$,'42501','blocked_profile_unavailable','Another viewer cannot inspect block recognition');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=1),true);
select is(jsonb_array_length(public.get_blocked_users()->'items'),1,'Viewing recognition never unblocks');
select public.unblock_user((select (value->>'id')::uuid from saved where label='block'));
select throws_ok($$select public.get_blocked_profile((select (value->>'id')::uuid from saved where label='block'))$$,'42501','blocked_profile_unavailable','Recognition capability disappears after explicit unblock');
reset role;
-- Trusted rollback-only ledger fixture keeps normal guard validation. No client award path.
select private.set_xp_award(owner,'WORD_COMPLETED','qa29:'||i,10,true,gen_random_uuid())
 from people cross join generate_series(1,10) i where n=2;
select is(public.get_public_profile((select id from people where n=2))->'profile'->>'level','3','Public Level derives exact signed-ledger boundary through shared helper');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=2),true);
select is(public.get_public_profile()->'profile'->>'level',public.get_my_progress()->>'level','Public and owner use the same authoritative level');
select private.set_xp_award(auth.uid(),'WORD_COMPLETED','qa29:1',10,false,gen_random_uuid());
select is(public.get_public_profile()->'profile'->>'level','2','Public level includes negative reversals instead of positive-only lifetime farming');
select set_config('request.jwt.claim.sub',(select owner::text from people where n=1),true);
update private.safety_accounts set restricted=true where user_id=(select owner from people where n=2);
select throws_ok($$select public.get_public_profile((select id from people where n=2))$$,'42501','profile_unavailable','Restricted subjects cannot disclose public level');
select public.begin_submission_deletion((select id from photos));
select is(public.get_explore_concept((select concept_id from concepts))->'item'->>'has_captures','false','Deleting last owned capture hides history action');
select ok((select relrowsecurity from pg_class where oid='private.inbox_openings'::regclass),'Opening receipts enforce RLS');
select ok(not has_function_privilege('authenticated','private.public_profile_level(uuid)','execute'),'Private level helper cannot bypass profile admission');
set local role anon;
select throws_ok($$select public.open_notification_inbox(gen_random_uuid())$$,'42501',null,'Anonymous inbox opening denied');
select throws_ok($$select public.get_blocked_profile(gen_random_uuid())$$,'42501',null,'Anonymous recognition denied');
reset role;
select * from finish();
rollback;
