// Color roles, not screen palettes. Keep surfaces neutral; use small semantic
// accents. brandText is the supplied stronger indigo for readable text on tints.
export const palette = {
  light: {
    background: '#F7F8F4',
    surface: '#FFFFFF',
    surfaceMuted: '#EDF0F4',
    textPrimary: '#192D32',
    textSecondary: '#5B6D72',
    brandPrimary: '#5B5CF6',
    brandPrimaryPressed: '#4748D8',
    brandText: '#4748D8',
    brandSoft: '#EEEDFF',
    textOnPrimary: '#FFFFFF',
    accentEnergy: '#FF7048',
    accentReward: '#F4C542',
    textOnAccent: '#192D32',
    // Slightly darker than the brief for small text on the neutral/error surfaces.
    success: '#1F805F',
    error: '#C13E3E',
    errorSoft: '#FCEEEE',
    warning: '#886013',
    border: '#DDE2E7',
    controlBorder: '#78868A',
    overlay: 'rgba(9, 24, 28, 0.42)',
    mediaBackground: '#111D21',
    mediaForeground: '#FFFFFF',
  },
  dark: {
    background: '#111D21',
    surface: '#1B2A2F',
    surfaceMuted: '#25343C',
    textPrimary: '#EFF5F2',
    textSecondary: '#B0C0C0',
    brandPrimary: '#8B8CFF',
    brandPrimaryPressed: '#A6A7FF',
    brandText: '#A6A7FF',
    brandSoft: '#2D2D4B',
    textOnPrimary: '#111D21',
    accentEnergy: '#FF8D6D',
    accentReward: '#FFD966',
    textOnAccent: '#192D32',
    success: '#64D7AD',
    error: '#FF9A9A',
    errorSoft: '#482B32',
    warning: '#EDC575',
    border: '#3B4850',
    controlBorder: '#78868A',
    overlay: 'rgba(0, 0, 0, 0.6)',
    mediaBackground: '#111D21',
    mediaForeground: '#FFFFFF',
  },
} as const;

export const spacing = { xs: 4, sm: 8, md: 12, lg: 20, xl: 28, xxl: 40 } as const;
export const radius = { sm: 10, md: 16, lg: 24, xl: 32 } as const;
